"""REBOOT product strings: EN source -> FR / ES / DE / IT.

Keys ARE the canonical English strings (String Catalog fallback design).
Voice: calm, precise, editorial. Non-clinical. Non-gamified. No idioms that
break tone. Mode names STAY / RECALL / EXPLAIN / NOTHING / OBSERVE and the
brand name REBOOT are never translated.
"""

STRINGS = {
    # ================= ONBOARDING =================
    "Your attention is being pulled apart.": {
        "fr": "Votre attention est en train d'être tirée en quatre.",
        "es": "Tu atención se está fragmentando.",
        "de": "Deine Aufmerksamkeit wird auseinandergerissen.",
        "it": "La tua attenzione viene spezzata.",
    },
    "Every notification, feed and interruption asks for the same thing: switch.": {
        "fr": "Chaque notification, chaque fil, chaque interruption demande la même chose : changer.",
        "es": "Cada notificación, cada feed, cada interrupción pide lo mismo: cambiar.",
        "de": "Jede Benachrichtigung, jeder Feed, jede Unterbrechung verlangt dasselbe: wechseln.",
        "it": "Ogni notifica, ogni feed, ogni interruzione chiede la stessa cosa: cambiare.",
    },
    "And what you repeat becomes easier to repeat.": {
        "fr": "Et ce que vous répétez devient plus facile à répéter.",
        "es": "Y lo que repites se vuelve más fácil de repetir.",
        "de": "Und was du wiederholst, wird leichter zu wiederholen.",
        "it": "E ciò che ripeti diventa più facile da ripetere.",
    },
    "See what's happening": {
        "fr": "Comprendre ce qui se passe",
        "es": "Ver qué está pasando",
        "de": "Verstehen, was passiert",
        "it": "Capire cosa succede",
    },
    "You're training yourself to switch.": {
        "fr": "Vous vous entraînez à changer d'attention.",
        "es": "Te estás entrenando para cambiar de tarea.",
        "de": "Du trainierst dich im Wechseln.",
        "it": "Ti stai allenando a cambiare.",
    },
    "Open. Scroll. Check. Change. Repeat.": {
        "fr": "Ouvrir. Faire défiler. Vérifier. Changer. Recommencer.",
        "es": "Abrir. Deslizar. Comprobar. Cambiar. Repetir.",
        "de": "Öffnen. Scrollen. Prüfen. Wechseln. Wiederholen.",
        "it": "Apri. Scorri. Controlli. Cambi. Ricominci.",
    },
    "The problem isn't that you've lost attention. Your environment keeps rewarding the opposite behaviour.": {
        "fr": "Le problème n'est pas que vous avez perdu votre attention. Votre environnement récompense sans cesse le comportement inverse.",
        "es": "El problema no es que hayas perdido atención. Tu entorno sigue premiando el comportamiento contrario.",
        "de": "Das Problem ist nicht, dass du deine Aufmerksamkeit verloren hast. Deine Umgebung belohnt ständig das Gegenteil.",
        "it": "Il problema non è che hai perso attenzione. Il tuo ambiente continua a premiare il comportamento opposto.",
    },
    "Cut the noise": {
        "fr": "Réduire le bruit",
        "es": "Cortar el ruido",
        "de": "Den Lärm abschalten",
        "it": "Taglia il rumore",
    },
    "Attention is a skill.": {
        "fr": "L'attention est une compétence.",
        "es": "La atención es una habilidad.",
        "de": "Aufmerksamkeit ist eine Fähigkeit.",
        "it": "L'attenzione è un'abilità.",
    },
    "Staying with one thing, returning after distraction and rebuilding what you learned can all be trained.": {
        "fr": "Rester sur une tâche, revenir après une distraction, approfondir ce que vous apprenez : tout cela peut s'entraîner.",
        "es": "Permanecer en una tarea, volver tras una distracción y profundizar lo aprendido se pueden entrenar.",
        "de": "Bei einer Sache bleiben, nach einer Ablenkung zurückkehren, Gelerntes vertiefen – all das lässt sich trainieren.",
        "it": "Restare su una cosa, tornare dopo una distrazione, approfondire ciò che hai imparato: tutto si può allenare.",
    },
    "REBOOT starts by measuring how you work today.": {
        "fr": "REBOOT commence par mesurer comment vous travaillez aujourd'hui.",
        "es": "REBOOT empieza midiendo cómo trabajas hoy.",
        "de": "REBOOT misst zuerst, wie du heute arbeitest.",
        "it": "REBOOT inizia misurando come lavori oggi.",
    },
    "Build my baseline": {
        "fr": "Établir mon point de départ",
        "es": "Crear mi punto de partida",
        "de": "Meinen Ausgangspunkt ermitteln",
        "it": "Crea la mia base",
    },
    "Less input. More depth.": {
        "fr": "Moins d'inputs. Plus de profondeur.",
        "es": "Menos estímulos. Más profundidad.",
        "de": "Weniger Input. Mehr Tiefe.",
        "it": "Meno input. Più profondità.",
    },
    "We'll change the conditions around you, train sustained attention, improve recall and help you design real deep-work sessions.": {
        "fr": "Nous modifierons vos conditions de travail, entraînerons l'attention soutenue, amélioreront la mémorisation et vous aideront à créer de vraies séances de travail profond.",
        "es": "Cambiaremos tus condiciones, entrenaremos la atención sostenida, mejoraremos la retención y te ayudaremos a diseñar sesiones reales de trabajo profundo.",
        "de": "Wir verändern deine Bedingungen, trainieren anhaltende Aufmerksamkeit, verbessern das Erinnern und helfen dir, echte Tiefenarbeit zu gestalten.",
        "it": "Cambieremo le condizioni intorno a te, alleneremo l'attenzione sostenuta, miglioreremo il ricordo e ti aiuteremo a creare vere sessioni di lavoro profondo.",
    },
    "No miracle. No dopamine detox. Just deliberate practice and better conditions.": {
        "fr": "Pas de miracle. Pas de « détox dopamine ». Juste une pratique délibérée et de meilleures conditions.",
        "es": "Nada milagroso. Nada de «detox de dopamina». Solo práctica deliberada y mejores condiciones.",
        "de": "Kein Wunder. Kein Dopamin-Detox. Nur bewusstes Üben und bessere Bedingungen.",
        "it": "Nessun miracolo. Nessun detox da dopamina. Solo pratica deliberata e condizioni migliori.",
    },
    "Show me the protocol": {
        "fr": "Voir le protocole",
        "es": "Ver el protocolo",
        "de": "Protokoll ansehen",
        "it": "Mostra il protocollo",
    },
    "90 days. Built around you.": {
        "fr": "90 jours. Construits autour de vous.",
        "es": "90 días. Diseñados a tu alrededor.",
        "de": "90 Tage. Um dich herum aufgebaut.",
        "it": "90 giorni. Costruiti intorno a te.",
    },
    "REBOOT learns from your sessions, experiments, environment, energy and Flow conditions — then adapts what comes next.": {
        "fr": "REBOOT apprend de vos séances, expériences, environnement, énergie et conditions de Flow — puis adapte la suite.",
        "es": "REBOOT aprende de tus sesiones, experimentos, entorno, energía y condiciones de Flow, y adapta lo que viene después.",
        "de": "REBOOT lernt aus deinen Sitzungen, Experimenten, deiner Umgebung, deiner Energie und deinen Flow-Bedingungen – und passt alles Weitere an.",
        "it": "REBOOT impara dalle tue sessioni, dai tuoi esperimenti, dall'ambiente, dall'energia e dalle condizioni di Flow, poi adatta ciò che segue.",
    },
    "No streak to protect. Miss a day and the program simply waits.": {
        "fr": "Aucune série à préserver. Un jour manqué et le programme attend, tout simplement.",
        "es": "Nada que perder por fallar un día. El programa simplemente espera.",
        "de": "Keine Serie zu verteidigen. Verpasst du einen Tag, wartet das Programm einfach.",
        "it": "Nessuna serie da proteggere. Se salti un giorno, il programma semplicemente aspetta.",
    },
    "Observe": {"fr": "Observer", "es": "Observar", "de": "Beobachten", "it": "Osservare"},
    "Adapt": {"fr": "S'adapter", "es": "Adaptarse", "de": "Anpassen", "it": "Adattarsi"},
    "Own it": {
        "fr": "En prendre le contrôle",
        "es": "Hacerlo tuyo",
        "de": "Selbst übernehmen",
        "it": "Renderlo tuo",
    },
    "One last thing": {
        "fr": "Une dernière chose",
        "es": "Una última cosa",
        "de": "Eine letzte Sache",
        "it": "Un'ultima cosa",
    },
    "Rebuild your attention.": {
        "fr": "Reconstruisez votre attention.",
        "es": "Reconstruye tu atención.",
        "de": "Baue deine Aufmerksamkeit neu auf.",
        "it": "Ricostruisci la tua attenzione.",
    },
    "The first week is calibration. We start with what you tell us, then REBOOT learns from what actually happens.": {
        "fr": "La première semaine sert d'étalonnage. Nous partons de ce que vous nous dites, puis REBOOT apprend de ce qui se passe vraiment.",
        "es": "La primera semana es de calibración. Empezamos con lo que nos cuentas y luego REBOOT aprende de lo que ocurre de verdad.",
        "de": "Die erste Woche ist Kalibrierung. Wir starten mit dem, was du uns sagst, dann lernt REBOOT aus dem, was wirklich passiert.",
        "it": "La prima settimana è di calibrazione. Partiamo da quello che ci dici, poi REBOOT impara da ciò che accade davvero.",
    },
    "Begin REBOOT": {"fr": "Commencer", "es": "Empezar", "de": "Beginnen", "it": "Inizia"},
    "Not now": {
        "fr": "Pas maintenant",
        "es": "Ahora no",
        "de": "Nicht jetzt",
        "it": "Non ora",
    },

    # ================= DIAGNOSIS QUESTIONS =================
    "What would feel meaningfully different 90 days from now?": {
        "fr": "Qu'est-ce qui serait vraiment différent dans 90 jours ?",
        "es": "¿Qué se sentiría realmente diferente dentro de 90 días?",
        "de": "Was würde sich nach 90 Tagen spürbar anders anfühlen?",
        "it": "Cosa si sentirebbe davvero diverso tra 90 giorni?",
    },
    "Choose everything that feels true.": {
        "fr": "Choisissez tout ce qui semble vrai.",
        "es": "Elige todo lo que sientas cierto.",
        "de": "Wähle alles, was sich richtig anfühlt.",
        "it": "Scegli tutto ciò che senti vero.",
    },
    "Work deeply for longer": {
        "fr": "Travailler en profondeur plus longtemps",
        "es": "Trabajar en profundidad durante más tiempo",
        "de": "Länger konzentriert tief arbeiten",
        "it": "Lavorare in profondità più a lungo",
    },
    "Stop compulsive checking": {
        "fr": "Arrêter les vérifications compulsives",
        "es": "Dejar de comprobar todo el tiempo",
        "de": "Aufhören, ständig zu checken",
        "it": "Smettere di controllare d'impulso",
    },
    "Stay with one thing": {
        "fr": "Rester concentré sur une seule chose",
        "es": "Permanecer en una sola cosa",
        "de": "Bei einer Sache bleiben",
        "it": "Restare su una cosa sola",
    },
    "Study without drifting": {
        "fr": "Étudier sans se disperser",
        "es": "Estudiar sin dispersarme",
        "de": "Ohne Abschweifen lernen",
        "it": "Studiare senza dispersione",
    },
    "Read with full attention": {
        "fr": "Lire avec toute son attention",
        "es": "Leer con toda la atención",
        "de": "Mit voller Aufmerksamkeit lesen",
        "it": "Leggere con tutta l'attenzione",
    },
    "Remember what I consume": {
        "fr": "Retenir ce que je consomme",
        "es": "Recordar lo que consumo",
        "de": "Behalten, was ich aufnehme",
        "it": "Ricordare ciò che consumo",
    },
    "Finish difficult tasks": {
        "fr": "Terminer les tâches difficiles",
        "es": "Terminar las tareas difíciles",
        "de": "Schwierige Aufgaben abschließen",
        "it": "Finire le attività difficili",
    },
    "A calmer relationship with my phone": {
        "fr": "Une relation plus calme avec mon téléphone",
        "es": "Una relación más tranquila con mi teléfono",
        "de": "Ein ruhigeres Verhältnis zum Handy",
        "it": "Un rapporto più sereno col telefono",
    },
    "Which part feels hardest right now?": {
        "fr": "Quelle partie semble la plus difficile en ce moment ?",
        "es": "¿Qué parte resulta más difícil ahora mismo?",
        "de": "Welcher Teil fühlt sich gerade am schwersten an?",
        "it": "Quale parte risulta più difficile adesso?",
    },
    "The honest one, not the most admirable one.": {
        "fr": "La réponse honnête, pas la plus admirable.",
        "es": "La respuesta sincera, no la más admirable.",
        "de": "Die ehrliche Antwort, nicht die bewundernswerteste.",
        "it": "La risposta sincera, non quella più ammirevole.",
    },
    "Getting started": {
        "fr": "Commencer",
        "es": "Empezar",
        "de": "Anfangen",
        "it": "Iniziare",
    },
    "Staying with one thing": {
        "fr": "Rester sur une même chose",
        "es": "Mantenerme en una cosa",
        "de": "Dranbleiben",
        "it": "Restare concentrato",
    },
    "Resisting the urge to check": {
        "fr": "Résister à l'envie de vérifier",
        "es": "Resistir las ganas de mirar el teléfono",
        "de": "Dem Check-Impuls widerstehen",
        "it": "Resistere alla voglia di controllare",
    },
    "Returning after an interruption": {
        "fr": "Revenir après une interruption",
        "es": "Volver tras una interrupción",
        "de": "Nach einer Unterbrechung zurückkehren",
        "it": "Tornare dopo un'interruzione",
    },
    "Remembering what I just read or watched": {
        "fr": "Retenir ce que je viens de lire ou de voir",
        "es": "Recordar lo que acabo de leer o ver",
        "de": "Behalten, was ich gerade gelesen oder gesehen habe",
        "it": "Ricordare cosa ho appena letto o visto",
    },
    "Quieting mental noise": {
        "fr": "Apaiser le bruit mental",
        "es": "Callar el ruido mental",
        "de": "Gedankenrauschen beruhigen",
        "it": "Silenzare il rumore mentale",
    },
    "Not sure yet": {
        "fr": "Je ne sais pas encore",
        "es": "Aún no lo sé",
        "de": "Weiß ich noch nicht",
        "it": "Non lo so ancora",
    },
    "Where does your attention break most?": {
        "fr": "Où votre attention se brise-t-elle le plus ?",
        "es": "¿Dónde se rompe más tu atención?",
        "de": "Wo bricht deine Aufmerksamkeit am häufigsten?",
        "it": "Dove si spezza di più la tua attenzione?",
    },
    "Where the break actually happens, not what bothers you most.": {
        "fr": "Là où la rupture se produit vraiment, pas ce qui vous déplaît le plus.",
        "es": "Donde ocurre de verdad, no lo que más molesta.",
        "de": "Wo der Abbruch wirklich passiert, nicht was dich am meisten stört.",
        "it": "Dove avviene davvero, non ciò che infastidisce di più.",
    },
    "The phone": {"fr": "Le téléphone", "es": "El teléfono", "de": "Das Handy", "it": "Il telefono"},
    "Notifications": {
        "fr": "Les notifications",
        "es": "Las notificaciones",
        "de": "Benachrichtigungen",
        "it": "Le notifiche",
    },
    "Social apps": {
        "fr": "Les réseaux sociaux",
        "es": "Las apps sociales",
        "de": "Social Apps",
        "it": "Le app social",
    },
    "Browser tabs": {
        "fr": "Les onglets du navigateur",
        "es": "Las pestañas del navegador",
        "de": "Browser-Tabs",
        "it": "Le schede del browser",
    },
    "My own thoughts": {
        "fr": "Mes propres pensées",
        "es": "Mis propios pensamientos",
        "de": "Meine eigenen Gedanken",
        "it": "I miei stessi pensieri",
    },
    "People around me": {
        "fr": "Les personnes autour de moi",
        "es": "La gente a mi alrededor",
        "de": "Menschen um mich herum",
        "it": "Le persone intorno",
    },
    "Tiredness": {"fr": "La fatigue", "es": "El cansancio", "de": "Müdigkeit", "it": "La stanchezza"},
    "Unclear": {"fr": "Pas clair", "es": "No lo tengo claro", "de": "Unklar", "it": "Non è chiaro"},
    "And if only one of these could fully change, which one?": {
        "fr": "Et si une seule de ces choses pouvait totalement changer, laquelle ?",
        "es": "Y si solo una pudiera cambiar por completo, ¿cuál?",
        "de": "Und wenn sich nur eine davon völlig ändern könnte – welche?",
        "it": "E se una sola di queste potesse cambiare del tutto, quale?",
    },
    "This becomes the direction everything else adapts around.": {
        "fr": "Elle devient la direction autour de laquelle tout le reste s'adapte.",
        "es": "Se convierte en la dirección sobre la que se adapta todo lo demás.",
        "de": "Sie wird zur Richtung, um die sich alles andere anpasst.",
        "it": "Diventa la direzione attorno alla quale si adatta tutto il resto.",
    },
    "When you start something demanding, how long before you usually feel pulled away?": {
        "fr": "Quand vous commencez une tâche exigeante, au bout de combien de temps vous sentez-vous généralement détourné ?",
        "es": "Cuando empiezas algo exigente, ¿cuánto tardas normalmente en sentirte arrastrado a otra cosa?",
        "de": "Wenn du etwas Anspruchsvolles beginnst – nach wie lange fühlst du dich meistens abgelenkt?",
        "it": "Quando inizi qualcosa di impegnativo, dopo quanto tempo di solito ti senti attratto altrove?",
    },
    "A typical day, not your best one.": {
        "fr": "Une journée ordinaire, pas votre meilleure.",
        "es": "Un día normal, no tu mejor día.",
        "de": "Ein typischer Tag, nicht dein bester.",
        "it": "Una giornata normale, non la migliore.",
    },
    "Under 5 minutes": {
        "fr": "Moins de 5 minutes",
        "es": "Menos de 5 minutos",
        "de": "Unter 5 Minuten",
        "it": "Meno di 5 minuti",
    },
    "5 – 15 minutes": {
        "fr": "5 – 15 minutes",
        "es": "5 – 15 minutos",
        "de": "5 – 15 Minuten",
        "it": "5 – 15 minuti",
    },
    "15 – 30 minutes": {
        "fr": "15 – 30 minutes",
        "es": "15 – 30 minutos",
        "de": "15 – 30 Minuten",
        "it": "15 – 30 minuti",
    },
    "30 – 60 minutes": {
        "fr": "30 – 60 minutes",
        "es": "30 – 60 minutos",
        "de": "30 – 60 Minuten",
        "it": "30 – 60 minuti",
    },
    "Usually past an hour": {
        "fr": "Généralement plus d'une heure",
        "es": "Normalmente más de una hora",
        "de": "Meist über eine Stunde",
        "it": "Di solito oltre un'ora",
    },
    "Depends heavily on the task": {
        "fr": "Cela dépend beaucoup de la tâche",
        "es": "Depende mucho de la tarea",
        "de": "Hängt stark von der Aufgabe ab",
        "it": "Dipende molto dall'attività",
    },
    "When the work becomes uncomfortable, what usually happens?": {
        "fr": "Quand le travail devient inconfortable, que se passe-t-il généralement ?",
        "es": "Cuando el trabajo se hace incómodo, ¿qué pasa normalmente?",
        "de": "Wenn die Arbeit unbequem wird, was passiert dann meistens?",
        "it": "Quando il lavoro diventa scomodo, cosa succede di solito?",
    },
    "I check my phone": {
        "fr": "Je vérifie mon téléphone",
        "es": "Miro mi teléfono",
        "de": "Ich checke mein Handy",
        "it": "Controllo il telefono",
    },
    "I open something else": {
        "fr": "J'ouvre autre chose",
        "es": "Abro otra cosa",
        "de": "Ich öffne etwas anderes",
        "it": "Apro altro",
    },
    "I keep going, but it loses depth": {
        "fr": "Je continue, mais ça perd en profondeur",
        "es": "Sigo, pero pierdo profundidad",
        "de": "Ich mache weiter, aber es verliert an Tiefe",
        "it": "Continuo, ma perde profondità",
    },
    "My mind wanders off": {
        "fr": "Mon esprit s'évade",
        "es": "Mi mente se va a otro lado",
        "de": "Meine Gedanken schweifen ab",
        "it": "La mente vaga altrove",
    },
    "I abandon the task": {
        "fr": "J'abandonne la tâche",
        "es": "Abandono la tarea",
        "de": "Ich gebe die Aufgabe auf",
        "it": "Abbandono l'attività",
    },
    "It varies": {"fr": "Ça varie", "es": "Varía", "de": "Es variiert", "it": "Varia"},
    "After getting distracted, what usually happens next?": {
        "fr": "Après une distraction, que se passe-t-il ensuite ?",
        "es": "Tras distraerte, ¿qué suele pasar después?",
        "de": "Was passiert meistens, nachdem du abgelenkt wurdest?",
        "it": "Dopo una distrazione, cosa succede di solito?",
    },
    "I come back fairly quickly": {
        "fr": "Je reviens assez vite",
        "es": "Vuelvo bastante rápido",
        "de": "Ich komme ziemlich schnell zurück",
        "it": "Torno abbastanza presto",
    },
    "Returning takes real effort": {
        "fr": "Revenir demande un vrai effort",
        "es": "Volver cuesta un esfuerzo real",
        "de": "Zurückkehren kostet echte Mühe",
        "it": "Tornare richiede un vero sforzo",
    },
    "I drift into something else instead": {
        "fr": "Je dérive vers autre chose à la place",
        "es": "Acabo derivando hacia otra cosa",
        "de": "Ich treibe stattdessen in etwas anderes",
        "it": "Finisco per derivare verso altro",
    },
    "The original task is usually lost": {
        "fr": "La tâche d'origine est généralement perdue",
        "es": "La tarea original suele perderse",
        "de": "Die ursprüngliche Aufgabe geht meist verloren",
        "it": "L'attività originale di solito si perde",
    },
    "What kind of work matters most right now?": {
        "fr": "Quel travail compte le plus pour vous en ce moment ?",
        "es": "¿Qué tipo de trabajo importa más ahora mismo?",
        "de": "Welche Art von Arbeit ist dir gerade am wichtigsten?",
        "it": "Che tipo di lavoro conta di più adesso?",
    },
    "REBOOT uses your real material, so it helps to know what it is.": {
        "fr": "REBOOT utilise votre vrai matériel, donc il est utile de savoir lequel.",
        "es": "REBOOT usa tu material real, así que ayuda saber cuál es.",
        "de": "REBOOT arbeitet mit deinem echten Material, daher hilft es, es zu kennen.",
        "it": "REBOOT usa il tuo materiale reale, quindi aiuta sapere qual è.",
    },
    "Studying": {"fr": "Étudier", "es": "Estudiar", "de": "Lernen", "it": "Studiare"},
    "Creative work": {
        "fr": "Travail créatif",
        "es": "Trabajo creativo",
        "de": "Kreative Arbeit",
        "it": "Lavoro creativo",
    },
    "Professional deep work": {
        "fr": "Travail professionnel en profondeur",
        "es": "Trabajo profesional en profundidad",
        "de": "Berufliche Tiefenarbeit",
        "it": "Lavoro professionale in profondità",
    },
    "Reading & learning": {
        "fr": "Lecture et apprentissage",
        "es": "Lectura y aprendizaje",
        "de": "Lesen und Lernen",
        "it": "Lettura e apprendimento",
    },
    "Building & coding": {
        "fr": "Construction et code",
        "es": "Construir y programar",
        "de": "Bauen und Programmieren",
        "it": "Costruire e programmare",
    },
    "A bit of everything": {
        "fr": "Un peu de tout",
        "es": "Un poco de todo",
        "de": "Ein bisschen von allem",
        "it": "Un po' di tutto",
    },
    "When does your attention naturally feel best?": {
        "fr": "Quand votre attention se sent-elle naturellement au mieux ?",
        "es": "¿Cuándo tu atención se siente naturalmente mejor?",
        "de": "Wann fühlt sich deine Aufmerksamkeit von Natur aus am besten an?",
        "it": "Quando la tua attenzione si sente naturalmente al meglio?",
    },
    "Early morning": {
        "fr": "Tôt le matin",
        "es": "Primera hora de la mañana",
        "de": "Früh am Morgen",
        "it": "Prima del mattino",
    },
    "Mid-morning": {
        "fr": "Milieu de matinée",
        "es": "Media mañana",
        "de": "Vormittag",
        "it": "Metà mattina",
    },
    "Afternoon": {"fr": "Après-midi", "es": "Tarde", "de": "Nachmittag", "it": "Pomeriggio"},
    "Evening": {"fr": "Soir", "es": "Noche", "de": "Abend", "it": "Sera"},
    "Late night": {
        "fr": "Fin de soirée",
        "es": "Madrugada",
        "de": "Späte Nacht",
        "it": "Tarda notte",
    },
    "No pattern I've noticed": {
        "fr": "Aucun schéma que j'aie remarqué",
        "es": "Ningún patrón que haya notado",
        "de": "Kein Muster, das ich bemerkt habe",
        "it": "Nessuno schema che abbia notato",
    },

    "Attention in general": {
        "fr": "L'attention en général",
        "es": "La atención en general",
        "de": "Aufmerksamkeit allgemein",
        "it": "L'attenzione in generale",
    },

    "Under 5 min": {
        "fr": "Moins de 5 min",
        "es": "Menos de 5 min",
        "de": "Unter 5 Min.",
        "it": "Meno di 5 min",
    },
    "60+ minutes": {
        "fr": "Plus de 60 minutes",
        "es": "Más de 60 minutos",
        "de": "Über 60 Minuten",
        "it": "Oltre 60 minuti",
    },
    # ================= STARTING POINT REPORT =================
    "Your starting point.": {
        "fr": "Votre point de départ.",
        "es": "Tu punto de partida.",
        "de": "Dein Ausgangspunkt.",
        "it": "Il tuo punto di partenza.",
    },
    "This is not a verdict. It is where REBOOT starts — and the first week begins replacing these answers with what actually happens.": {
        "fr": "Ce n'est pas un verdict. C'est là où REBOOT commence — et la première semaine remplace ces réponses par ce qui se passe réellement.",
        "es": "Esto no es un veredicto. Es donde empieza REBOOT, y la primera semana comienza a sustituir estas respuestas por lo que ocurre de verdad.",
        "de": "Dies ist kein Urteil. Hier beginnt REBOOT – und die erste Woche ersetzt diese Antworten durch das, was wirklich passiert.",
        "it": "Questo non è un verdetto. È dove REBOOT inizia, e la prima settimana comincia a sostituire queste risposte con ciò che accade davvero.",
    },
    "You told reboot": {
        "fr": "Vous avez dit à reboot",
        "es": "Le dijiste a reboot",
        "de": "Du hast reboot gesagt",
        "it": "Hai detto a reboot",
    },
    "Not chosen yet": {
        "fr": "Pas encore choisi",
        "es": "Aún sin elegir",
        "de": "Noch nicht gewählt",
        "it": "Non ancora scelto",
    },
    "Still unclear — Day 1 watches for it": {
        "fr": "Encore flou — le Jour 1 y veille",
        "es": "Todavía sin claridad — el Día 1 lo observará",
        "de": "Noch unklar – Tag 1 achtet darauf",
        "it": "Ancora poco chiaro — il Giorno 1 osserverà",
    },
    "Main breaker": {
        "fr": "Principale source de rupture",
        "es": "Principal fuente de ruptura",
        "de": "Hauptunterbrecher",
        "it": "Principale causa di rottura",
    },
    "Not identified yet": {
        "fr": "Pas encore identifié",
        "es": "Aún sin identificar",
        "de": "Noch nicht identifiziert",
        "it": "Non ancora identificato",
    },
    "Focus window": {
        "fr": "Fenêtre d'attention",
        "es": "Ventana de atención",
        "de": "Fokusfenster",
        "it": "Finestra di attenzione",
    },
    "Unmeasured": {
        "fr": "Non mesuré",
        "es": "Sin medir",
        "de": "Ungemessen",
        "it": "Non misurato",
    },
    "Returning after distraction": {
        "fr": "Le retour après distraction",
        "es": "Volver tras la distracción",
        "de": "Rückkehr nach Ablenkung",
        "it": "Il ritorno dopo la distrazione",
    },
    "When it gets hard": {
        "fr": "Quand ça devient difficile",
        "es": "Cuando se pone difícil",
        "de": "Wenn es schwer wird",
        "it": "Quando diventa difficile",
    },
    "Work that matters now": {
        "fr": "Le travail qui compte maintenant",
        "es": "El trabajo que importa ahora",
        "de": "Arbeit, die jetzt zählt",
        "it": "Il lavoro che conta ora",
    },
    "Best hours": {
        "fr": "Meilleures heures",
        "es": "Mejores horas",
        "de": "Beste Stunden",
        "it": "Migliori ore",
    },
    "What you told us": {
        "fr": "Ce que vous nous avez dit",
        "es": "Lo que nos contaste",
        "de": "Was du uns gesagt hast",
        "it": "Cosa ci hai detto",
    },
    "Hardest part": {
        "fr": "Partie la plus difficile",
        "es": "Lo más difícil",
        "de": "Der schwerste Teil",
        "it": "La parte più difficile",
    },
    "Early morning ": {
        "fr": "Tôt le matin ",
        "es": "Primera hora ",
        "de": "Frühmorgens ",
        "it": "Primo mattino ",
    },
    "Mid-morning ": {
        "fr": "Milieu de matinée ",
        "es": "Media mañana ",
        "de": "Vormittag ",
        "it": "Metà mattina ",
    },
    "What reboot will learn instead": {
        "fr": "Ce que reboot apprendra à la place",
        "es": "Lo que reboot aprenderá en su lugar",
        "de": "Was reboot stattdessen lernt",
        "it": "Cosa imparerà reboot invece",
    },
    "Your real focus window, measured across sessions.": {
        "fr": "Votre vraie fenêtre d'attention, mesurée sur plusieurs séances.",
        "es": "Tu verdadera ventana de atención, medida entre sesiones.",
        "de": "Dein echtes Fokusfenster, über Sitzungen hinweg gemessen.",
        "it": "La tua vera finestra di attenzione, misurata sulle sessioni.",
    },
    "Whether the phone actually pulls you, or something else does.": {
        "fr": "Si c'est vraiment le téléphone qui vous attire — ou autre chose.",
        "es": "Si realmente te atrae el teléfono, o es otra cosa.",
        "de": "Ob wirklich das Handy zieht – oder etwas anderes.",
        "it": "Se è davvero il telefono ad attrarti, o qualcos'altro.",
    },
    "How quickly you return — and what makes returning easier.": {
        "fr": "À quelle vitesse vous revenez — et ce qui facilite le retour.",
        "es": "Qué tan rápido vuelves, y qué facilita el regreso.",
        "de": "Wie schnell du zurückkommst – und was die Rückkehr erleichtert.",
        "it": "Quanto rapidamente torni, e cosa rende il ritorno più facile.",
    },
    "Which conditions hold your deeper work.": {
        "fr": "Les conditions qui soutiennent votre travail en profondeur.",
        "es": "Qué condiciones sostienen tu trabajo profundo.",
        "de": "Welche Bedingungen deine Tiefenarbeit tragen.",
        "it": "Quali condizioni sostengono il tuo lavoro profondo.",
    },
    "None of these stay fixed. Observed evidence outweighs every answer above.": {
        "fr": "Rien de tout cela n'est figé. Les observations priment sur chaque réponse ci-dessus.",
        "es": "Nada de esto queda fijo. La evidencia observada pesa más que cada respuesta anterior.",
        "de": "Nichts davon bleibt fest. Beobachtete Evidenz wiegt schwerer als jede Antwort oben.",
        "it": "Nulla di questo resta fisso. L'evidenza osservata pesa più di ogni risposta sopra.",
    },
    "Status: Calibrating": {
        "fr": "Statut : étalonnage",
        "es": "Estado: calibrando",
        "de": "Status: Kalibrierung",
        "it": "Stato: calibrazione",
    },
    "Day 1 of 90 · your plan adapts as REBOOT observes you": {
        "fr": "Jour 1 sur 90 · votre plan s'adapte pendant que REBOOT vous observe",
        "es": "Día 1 de 90 · tu plan se adapta mientras REBOOT te observa",
        "de": "Tag 1 von 90 · dein Plan passt sich an, während REBOOT dich beobachtet",
        "it": "Giorno 1 di 90 · il tuo piano si adatta mentre REBOOT ti osserva",
    },
    "Start day one": {
        "fr": "Commencer le jour un",
        "es": "Empezar el día uno",
        "de": "Tag eins beginnen",
        "it": "Inizia il giorno uno",
    },
    "Retake the diagnosis": {
        "fr": "Refaire le diagnostic",
        "es": "Repetir el diagnóstico",
        "de": "Diagnose wiederholen",
        "it": "Rifare la diagnosi",
    },
    "REBOOT trains attention behaviors. It doesn't diagnose anything or measure your brain.": {
        "fr": "REBOOT entraîne des comportements d'attention. Il ne diagnostique rien et ne mesure pas votre cerveau.",
        "es": "REBOOT entrena comportamientos de atención. No diagnostica nada ni mide tu cerebro.",
        "de": "REBOOT trainiert Aufmerksamkeitsverhalten. Es diagnostiziert nichts und misst dein Gehirn nicht.",
        "it": "REBOOT allena comportamenti dell'attenzione. Non diagnostica nulla e non misura il tuo cervello.",
    },

    # ================= SHELL / COMMON =================
    "Today": {"fr": "Aujourd'hui", "es": "Hoy", "de": "Heute", "it": "Oggi"},
    "Train": {"fr": "S'entraîner", "es": "Entrenar", "de": "Training", "it": "Allenati"},
    "Program": {"fr": "Programme", "es": "Programa", "de": "Programm", "it": "Programma"},
    "Profile": {"fr": "Profil", "es": "Perfil", "de": "Profil", "it": "Profilo"},
    "Done": {"fr": "OK", "es": "Listo", "de": "Fertig", "it": "Fatto"},
    "Cancel": {"fr": "Annuler", "es": "Cancelar", "de": "Abbrechen", "it": "Annulla"},
    "Continue": {"fr": "Continuer", "es": "Continuar", "de": "Weiter", "it": "Continua"},
    "Close": {"fr": "Fermer", "es": "Cerrar", "de": "Schließen", "it": "Chiudi"},

    # ================= TODAY =================
    "COMPLETE": {"fr": "TERMINÉ", "es": "COMPLETADO", "de": "ABGESCHLOSSEN", "it": "COMPLETATO"},
    "OWN MODE": {"fr": "MODE PROPRE", "es": "MODO PROPIO", "de": "EIGENER MODUS", "it": "MODO PROPRIO"},
    "BEFORE YOU START": {
        "fr": "AVANT DE COMMENCER",
        "es": "ANTES DE EMPEZAR",
        "de": "BEVOR DU BEGINNST",
        "it": "PRIMA DI INIZIARE",
    },
    "Done — I'm set up": {
        "fr": "C'est fait — je suis prêt",
        "es": "Hecho — estoy listo",
        "de": "Erledigt – bin bereit",
        "it": "Fatto — sono pronto",
    },
    "Can't today": {
        "fr": "Impossible aujourd'hui",
        "es": "Hoy no puedo",
        "de": "Heute nicht möglich",
        "it": "Oggi non posso",
    },
    "Today's session is complete.": {
        "fr": "La séance du jour est terminée.",
        "es": "La sesión de hoy está completa.",
        "de": "Die heutige Sitzung ist abgeschlossen.",
        "it": "La sessione di oggi è completata.",
    },
    "Avg focus": {"fr": "Focus moy.", "es": "Focus medio", "de": "Ø Fokus", "it": "Focus medio"},
    "Return": {"fr": "Retour", "es": "Retorno", "de": "Rückkehr", "it": "Ritorno"},
    "Strong": {"fr": "Fort", "es": "Fuerte", "de": "Stark", "it": "Forte"},
    "Fair": {"fr": "Correct", "es": "Aceptable", "de": "Ordentlich", "it": "Discreto"},
    "Weak": {"fr": "Faible", "es": "Débil", "de": "Schwach", "it": "Debole"},
    "min": {"fr": "min", "es": "min", "de": "Min.", "it": "min"},
    "One session recorded. REBOOT is still learning your patterns.": {
        "fr": "Une séance enregistrée. REBOOT apprend encore vos schémas.",
        "es": "Una sesión registrada. REBOOT todavía aprende tus patrones.",
        "de": "Eine Sitzung erfasst. REBOOT lernt noch deine Muster.",
        "it": "Una sessione registrata. REBOOT sta ancora imparando i tuoi schemi.",
    },
    "Nothing measured yet — Day 1 starts the record.": {
        "fr": "Rien de mesuré encore — le Jour 1 ouvre le dossier.",
        "es": "Nada medido aún — el Día 1 abre el historial.",
        "de": "Noch nichts gemessen – Tag 1 beginnt die Aufzeichnung.",
        "it": "Niente misurato ancora — il Giorno 1 apre il registro.",
    },
    "Your Attention Operating Manual remains alive and evolving.": {
        "fr": "Votre Manuel d'attention reste vivant et évolue.",
        "es": "Tu Manual de Atención sigue vivo y evolucionando.",
        "de": "Dein Aufmerksamkeits-Handbuch bleibt lebendig und entwickelt sich weiter.",
        "it": "Il tuo Manuale dell'Attenzione resta vivo e in evoluzione.",
    },
    "What happens today changes what comes next.": {
        "fr": "Ce qui se passe aujourd'hui change ce qui vient ensuite.",
        "es": "Lo que pasa hoy cambia lo que viene después.",
        "de": "Was heute passiert, verändert, was kommt.",
        "it": "Ciò che accade oggi cambia ciò che verrà.",
    },
    "Nothing needs adjusting today.": {
        "fr": "Rien à ajuster aujourd'hui.",
        "es": "Hoy no hay nada que ajustar.",
        "de": "Heute ist nichts anzupassen.",
        "it": "Oggi niente da sistemare.",
    },
    "NOTHING NEEDED": {
        "fr": "RIEN À FAIRE",
        "es": "NADA NECESARIO",
        "de": "NICHTS NÖTIG",
        "it": "NULLA DI NECESSARIO",
    },
    "SELF-DIRECTED": {
        "fr": "AUTONOME",
        "es": "AUTODIRIGIDO",
        "de": "SELBSTGESTEUERT",
        "it": "AUTODIRETTO",
    },
    "Open Operating Manual": {
        "fr": "Ouvrir le manuel d'attention",
        "es": "Abrir el manual de atención",
        "de": "Handbuch öffnen",
        "it": "Apri il manuale dell'attenzione",
    },
    "Opens the Attention Operating Manual": {
        "fr": "Ouvre le manuel d'attention",
        "es": "Abre el manual de atención",
        "de": "Öffnet das Aufmerksamkeits-Handbuch",
        "it": "Apre il manuale dell'attenzione",
    },
    "Opens the suggested destination": {
        "fr": "Ouvre la destination suggérée",
        "es": "Abre el destino sugerido",
        "de": "Öffnet das vorgeschlagene Ziel",
        "it": "Apre la destinazione suggerita",
    },
    "%d of %d program days completed": {
        "fr": "%d jours de programme complétés sur %d",
        "es": "%d de %d días de programa completados",
        "de": "%d von %d Programmtagen abgeschlossen",
        "it": "%d di %d giorni di programma completati",
    },
    "90 protocol days complete": {
        "fr": "90 jours de protocole terminés",
        "es": "90 días de protocolo completados",
        "de": "90 Protokolltage abgeschlossen",
        "it": "90 giorni di protocollo completati",
    },

    # ================= PAYWALL =================
    "paywall.price.year": {
        "en": "%@/year · cancel anytime",
        "fr": "%@/an · résiliable à tout moment",
        "es": "%@/año · cancela cuando quieras",
        "de": "%@/Jahr · jederzeit kündbar",
        "it": "%@/anno · cancella quando vuoi",
    },
    "paywall.price.month": {
        "en": "%@/month · billed monthly",
        "fr": "%@/mois · facturé mensuellement",
        "es": "%@/mes · facturación mensual",
        "de": "%@/Monat · monatliche Abrechnung",
        "it": "%@/mese · fatturazione mensile",
    },
    "paywall.unavailable": {
        "en": "Plans unavailable right now — check your connection and retry.",
        "fr": "Offres indisponibles pour le moment — vérifiez votre connexion puis réessayez.",
        "es": "Planes no disponibles ahora mismo — revisa tu conexión e inténtalo de nuevo.",
        "de": "Tarife gerade nicht verfügbar – Verbindung prüfen und erneut versuchen.",
        "it": "Piani non disponibili al momento — controlla la connessione e riprova.",
    },
    "Yearly": {"fr": "Annuel", "es": "Anual", "de": "Jährlich", "it": "Annuale"},
    "Monthly": {"fr": "Mensuel", "es": "Mensual", "de": "Monatlich", "it": "Mensile"},
    "7-day free trial": {
        "fr": "Essai gratuit de 7 jours",
        "es": "Prueba gratis de 7 días",
        "de": "7 Tage kostenlos testen",
        "it": "Prova gratuita di 7 giorni",
    },
    "Best value": {"fr": "Meilleure offre", "es": "Mejor precio", "de": "Bestes Angebot", "it": "Miglior prezzo"},
    "Start 7-Day Free Trial": {
        "fr": "Démarrer l'essai de 7 jours",
        "es": "Empezar prueba de 7 días",
        "de": "7-Tage-Test starten",
        "it": "Inizia la prova di 7 giorni",
    },
    "Continue the full program": {
        "fr": "Continuer le programme complet",
        "es": "Continuar el programa completo",
        "de": "Vollständiges Programm fortsetzen",
        "it": "Continua il programma completo",
    },
    "Restore purchases": {
        "fr": "Restaurer les achats",
        "es": "Restaurar compras",
        "de": "Käufe wiederherstellen",
        "it": "Ripristina acquisti",
    },
    "Terms of Service": {
        "fr": "Conditions d'utilisation",
        "es": "Términos del servicio",
        "de": "Nutzungsbedingungen",
        "it": "Termini di servizio",
    },
    "Privacy Policy": {
        "fr": "Politique de confidentialité",
        "es": "Política de privacidad",
        "de": "Datenschutzrichtlinie",
        "it": "Informativa sulla privacy",
    },
    "Subscriptions renew automatically unless canceled at least 24 hours before the end of the current billing cycle in your Apple ID Account Settings.": {
        "fr": "Les abonnements se renouvellent automatiquement sauf annulation au moins 24 h avant la fin de la période en cours dans les réglages de votre identifiant Apple.",
        "es": "Las suscripciones se renuevan automáticamente salvo cancelación al menos 24 horas antes del fin del ciclo actual en los ajustes de tu ID de Apple.",
        "de": "Abos verlängern sich automatisch, sofern nicht mindestens 24 Stunden vor Ende des aktuellen Zeitraums in den Apple-ID-Einstellungen gekündigt wird.",
        "it": "Gli abbonamenti si rinnovano automaticamente salvo disdetta almeno 24 ore prima della fine del periodo corrente nelle impostazioni dell'ID Apple.",
    },
    "UNDERSTAND": {"fr": "COMPRENDRE", "es": "ENTENDER", "de": "VERSTEHEN", "it": "CAPIRE"},
    "TRAIN": {"fr": "S'ENTRAÎNER", "es": "ENTRENAR", "de": "TRAINIEREN", "it": "ALLENARE"},
    "RESHAPE": {"fr": "REMODOLER", "es": "REMODELAR", "de": "UMGESTALTEN", "it": "RIDISEGNARE"},
    "LEARN": {"fr": "APPRENDRE", "es": "APRENDER", "de": "LERNEN", "it": "IMPARARE"},
    "LEAVE": {"fr": "TRANSMETTRE", "es": "DEJAR", "de": "ÜBERGEBEN", "it": "LASCIARE"},
    "What breaks your attention": {
        "fr": "Ce qui brise votre attention",
        "es": "Qué rompe tu atención",
        "de": "Was deine Aufmerksamkeit bricht",
        "it": "Cosa spezza la tua attenzione",
    },
    "Your sessions and honest self-reports surface the pulls that actually cost you focus.": {
        "fr": "Vos séances et vos réponses honnêtes révèlent les forces qui coûtent vraiment votre attention.",
        "es": "Tus sesiones y autoinformes sinceros revelan los impulsos que de verdad te cuestan foco.",
        "de": "Deine Sitzungen und ehrlichen Selbstauskünfte zeigen die Kräfte, die wirklich Fokus kosten.",
        "it": "Sessioni e autovalutazioni oneste rivelano gli impulsi che davvero ti costano concentrazione.",
    },
    "Staying, returning, recalling": {
        "fr": "Rester, revenir, retenir",
        "es": "Permanecer, volver, recordar",
        "de": "Bleiben, kehren, behalten",
        "it": "Restare, tornare, ricordare",
    },
    "One prescribed practice a day across five attention modes.": {
        "fr": "Une pratique prescrite par jour, parmi cinq modes d'attention.",
        "es": "Una práctica diaria recetada entre cinco modos de atención.",
        "de": "Eine tägliche Übung aus fünf Aufmerksamkeitsmodi.",
        "it": "Una pratica al giorno tra cinque modalità di attenzione.",
    },
    "Your environment": {
        "fr": "Votre environnement",
        "es": "Tu entorno",
        "de": "Deine Umgebung",
        "it": "Il tuo ambiente",
    },
    "Lighter friction first — distance, one-task browser, optional protection.": {
        "fr": "D'abord les frictions les plus légères — distance, navigateur à tâche unique, protection facultative.",
        "es": "Primero la fricción más ligera — distancia, navegador de una sola tarea, protección opcional.",
        "de": "Zuerst die leichteste Reibung – Abstand, Ein-Aufgaben-Browser, optionaler Schutz.",
        "it": "Prima l'attrito più leggero — distanza, browser a attività singola, protezione facoltativa.",
    },
    "The conditions that help you": {
        "fr": "Les conditions qui vous aident",
        "es": "Las condiciones que te ayudan",
        "de": "Die Bedingungen, die dir helfen",
        "it": "Le condizioni che ti aiutano",
    },
    "Tested against your own comparable sessions, not averages.": {
        "fr": "Testées contre vos propres séances comparables, pas des moyennes.",
        "es": "Probadas contra tus propias sesiones comparables, no contra promedios.",
        "de": "Getestet an deinen eigenen vergleichbaren Sitzungen, nicht an Durchschnitten.",
        "it": "Verificate sulle tue sessioni comparabili, non su medie.",
    },
    "An Operating Manual that's yours": {
        "fr": "Un manuel qui vous appartient",
        "es": "Un manual que es tuyo",
        "de": "Ein Handbuch, das dir gehört",
        "it": "Un manuale che è tuo",
    },
    "Day 90 ends with your evidence-backed manual; Own Mode keeps it useful.": {
        "fr": "Le jour 90 s'achève sur votre manuel fondé sur preuves ; le Mode propre le garde utile.",
        "es": "El día 90 termina con tu manual basado en evidencia; el Modo Propio lo mantiene útil.",
        "de": "Tag 90 endet mit deinem evidenzbasierten Handbuch; der Eigene Modus hält es nützlich.",
        "it": "Il giorno 90 si chiude col tuo manuale basato sull'evidenza; il Modo Proprio lo tiene utile.",
    },

    # ================= DAY 1 CONTINUATION =================
    "DAY 1 COMPLETE": {
        "fr": "JOUR 1 TERMINÉ",
        "es": "DÍA 1 COMPLETADO",
        "de": "TAG 1 ABGESCHLOSSEN",
        "it": "GIORNO 1 COMPLETATO",
    },
    "Your baseline is set.": {
        "fr": "Votre point de référence est posé.",
        "es": "Tu punto de referencia está fijado.",
        "de": "Dein Referenzpunkt steht.",
        "it": "Il tuo punto di riferimento è fissato.",
    },
    "REBOOT now knows how today felt — and everything from here is measured against it. Each session teaches the program something new about how your attention actually works.": {
        "fr": "REBOOT sait désormais comment ce jour s'est passé — et tout la suite se mesurera à cette référence. Chaque séance apprend au programme quelque chose de nouveau sur votre attention réelle.",
        "es": "REBOOT ya sabe cómo se sintió hoy, y todo lo que sigue se medirá contra eso. Cada sesión enseña al programa algo nuevo sobre cómo funciona realmente tu atención.",
        "de": "REBOOT weiß jetzt, wie sich dieser Tag angefühlt hat – alles Weitere wird daran gemessen. Jede Sitzung bringt dem Programm etwas Neues darüber bei, wie deine Aufmerksamkeit wirklich arbeitet.",
        "it": "REBOOT ormai sa com'è andata oggi, e tutto ciò che seguirà verrà misurato su questo. Ogni sessione insegna al programma qualcosa di nuovo su come funziona davvero la tua attenzione.",
    },
    "FIRST INSIGHT": {
        "fr": "PREMIÈRE OBSERVATION",
        "es": "PRIMERA OBSERVACIÓN",
        "de": "ERSTE ERKENNTNIS",
        "it": "PRIMA OSSERVAZIONE",
    },
    "Continue the 90-day program": {
        "fr": "Continuer le programme de 90 jours",
        "es": "Continuar el programa de 90 días",
        "de": "Das 90-Tage-Programm fortsetzen",
        "it": "Continua il programma di 90 giorni",
    },
    "The full program continues with a subscription. Your Day 1 session and insights stay yours either way.": {
        "fr": "La suite du programme nécessite un abonnement. Votre séance du Jour 1 et vos observations restent les vôtres dans tous les cas.",
        "es": "El programa completo continúa con una suscripción. Tu sesión del Día 1 y sus observaciones siguen siendo tuyas de todos modos.",
        "de": "Das volle Programm setzt mit einem Abo fort. Deine Tag-1-Sitzung und Erkenntnisse bleiben in jedem Fall deine.",
        "it": "Il programma completo continua con un abbonamento. La sessione del Giorno 1 e le osservazioni restano tue in ogni caso.",
    },

    # ================= DATA & PRIVACY =================
    "DATA & PRIVACY": {
        "fr": "DONNÉES & CONFIDENTIALITÉ",
        "es": "DATOS Y PRIVACIDAD",
        "de": "DATEN & DATENSCHUTZ",
        "it": "DATI E PRIVACY",
    },
    "Your attention, fully local": {
        "fr": "Votre attention, entièrement locale",
        "es": "Tu atención, completamente local",
        "de": "Deine Aufmerksamkeit, komplett lokal",
        "it": "La tua attenzione, interamente locale",
    },
    "REBOOT keeps everything on this device. There is no account, no cloud profile, and no analytics.": {
        "fr": "REBOOT conserve tout sur cet appareil. Aucun compte, aucun profil cloud, aucune analytique.",
        "es": "REBOOT guarda todo en este dispositivo. Sin cuentas, sin perfiles en la nube, sin analíticas.",
        "de": "REBOOT bewahrt alles auf diesem Gerät auf. Kein Konto, kein Cloud-Profil, keine Analyse-Tools.",
        "it": "REBOOT tiene tutto su questo dispositivo. Nessun account, nessun profilo cloud, nessuna analitica.",
    },
    "On-device storage only": {
        "fr": "Stockage uniquement sur l'appareil",
        "es": "Almacenamiento solo en el dispositivo",
        "de": "Speicherung nur auf dem Gerät",
        "it": "Archiviazione solo sul dispositivo",
    },
    "Diagnosis answers, session records, switch and return evidence, personal rules, experiment results, Fuel context, Flow projects, environment settings, and your Operating Manual are stored in the app's local sandbox on this iPhone. Nothing is transmitted to REBOOT or to anyone else.": {
        "fr": "Réponses du diagnostic, séances, preuves de changement et de retour, règles personnelles, résultats d'expériences, contexte Fuel, projets Flow, réglages d'environnement et votre Manuel sont stockés dans le bac à sable local de l'app sur cet iPhone. Rien n'est transmis à REBOOT ni à quiconque.",
        "es": "Respuestas del diagnóstico, sesiones, evidencia de cambios y retornos, reglas personales, resultados de experimentos, contexto Fuel, proyectos Flow, ajustes de entorno y tu Manual se guardan en el sandbox local de la app en este iPhone. Nada se transmite a REBOOT ni a nadie.",
        "de": "Antworten der Diagnose, Sitzungen, Wechsel- und Rückkehr-Evidenz, persönliche Regeln, Experimentresultate, Fuel-Kontext, Flow-Projekte, Umgebungseinstellungen und dein Handbuch liegen im lokalen Sandbox-Speicher der App auf diesem iPhone. Nichts wird an REBOOT oder Dritte übertragen.",
        "it": "Risposte della diagnosi, sessioni, evidenze di cambio e ritorno, regole personali, risultati degli esperimenti, contesto Fuel, progetti Flow, impostazioni d'ambiente e il tuo Manuale sono archiviati nella sandbox locale dell'app su questo iPhone. Nulla viene trasmesso a REBOOT o ad altri.",
    },
    "Export my REBOOT data": {
        "fr": "Exporter mes données REBOOT",
        "es": "Exportar mis datos de REBOOT",
        "de": "Meine REBOOT-Daten exportieren",
        "it": "Esporta i miei dati REBOOT",
    },
    "A single JSON file containing everything REBOOT knows: diagnosis answers, profile, sessions, rules, experiments, Flow projects and evidence, Fuel history, environment observations, reviews, and your Operating Manual. Nothing leaves your device except through the share sheet you control.": {
        "fr": "Un seul fichier JSON avec tout ce que REBOOT sait : réponses du diagnostic, profil, séances, règles, expériences, projets et preuves Flow, historique Fuel, observations d'environnement, revues et votre Manuel. Rien ne quitte votre appareil sauf via la feuille de partage que vous contrôlez.",
        "es": "Un único archivo JSON con todo lo que REBOOT sabe: respuestas del diagnóstico, perfil, sesiones, reglas, experimentos, proyectos y evidencia Flow, historial Fuel, observaciones del entorno, revisiones y tu Manual. Nada sale de tu dispositivo salvo por la hoja de compartir que tú controlas.",
        "de": "Eine einzige JSON-Datei mit allem, was REBOOT weiß: Diagnoseantworten, Profil, Sitzungen, Regeln, Experimente, Flow-Projekte und -Evidenz, Fuel-Verlauf, Umgebungsbeobachtungen, Reviews und dein Handbuch. Nichts verlässt dein Gerät außer über das Share-Sheet, das du steuerst.",
        "it": "Un unico file JSON con tutto ciò che REBOOT sa: risposte della diagnosi, profilo, sessioni, regole, esperimenti, progetti ed evidenze Flow, cronologia Fuel, osservazioni d'ambiente, revisioni e il tuo Manuale. Nulla lascia il tuo dispositivo se non tramite il foglio di condivisione che controlli.",
    },
    "Export as JSON": {
        "fr": "Exporter en JSON",
        "es": "Exportar como JSON",
        "de": "Als JSON exportieren",
        "it": "Esporta come JSON",
    },
    "Legal": {"fr": "Mentions légales", "es": "Legal", "de": "Rechtliches", "it": "Legale"},
    "Erase all data": {
        "fr": "Effacer toutes les données",
        "es": "Borrar todos los datos",
        "de": "Alle Daten löschen",
        "it": "Cancella tutti i dati",
    },
    "Permanently deletes everything REBOOT has learned — sessions, profile, rules, experiments, Flow projects, environment setup, notifications, and your Operating Manual — and returns the app to its first launch. Screen Time authorization and notification permission are Apple settings and remain; scheduled protections are removed.": {
        "fr": "Supprime définitivement tout ce que REBOOT a appris — séances, profil, règles, expériences, projets Flow, environnement, notifications et votre Manuel — et ramène l'app à son premier lancement. L'autorisation Temps d'écran et les notifications restent des réglages Apple ; les protections programmées sont retirées.",
        "es": "Borra definitivamente todo lo que REBOOT ha aprendido — sesiones, perfil, reglas, experimentos, proyectos Flow, entorno, notificaciones y tu Manual — y devuelve la app a su primer arranque. La autorización de Tiempo de uso y los permisos de notificación son ajustes de Apple y permanecen; las protecciones programadas se eliminan.",
        "de": "Löscht endgültig alles, was REBOOT gelernt hat — Sitzungen, Profil, Regeln, Experimente, Flow-Projekte, Umgebung, Mitteilungen und dein Handbuch — und bringt die App auf ihren ersten Start zurück. Bildschirmzeit-Freigabe und Mitteilungszugriff bleiben Apple-Einstellungen; geplante Schutzschichten werden entfernt.",
        "it": "Cancella definitivamente tutto ciò che REBOOT ha imparato — sessioni, profilo, regole, esperimenti, progetti Flow, ambiente, notifiche e il tuo Manuale — e riporta l'app al primo avvio. L'autorizzazione Tempo di utilizzo e le notifiche restano impostazioni Apple; le protezioni pianificate vengono rimosse.",
    },
    "I understand this cannot be undone": {
        "fr": "Je comprends que cette action est irréversible",
        "es": "Entiendo que esto no se puede deshacer",
        "de": "Ich verstehe, dass dies nicht rückgängig gemacht werden kann",
        "it": "Capisco che non si può annullare",
    },
    "Erase All REBOOT Data": {
        "fr": "Effacer toutes les données REBOOT",
        "es": "Borrar todos los datos de REBOOT",
        "de": "Alle REBOOT-Daten löschen",
        "it": "Cancella tutti i dati REBOOT",
    },
    "Erase all REBOOT data?": {
        "fr": "Effacer toutes les données REBOOT ?",
        "es": "¿Borrar todos los datos de REBOOT?",
        "de": "Alle REBOOT-Daten löschen?",
        "it": "Cancellare tutti i dati REBOOT?",
    },
    "Continue": {"fr": "Continuer", "es": "Continuar", "de": "Fortfahren", "it": "Continua"},
    "This permanently deletes your sessions, profile, rules, experiments, environment setup, and Operating Manual from this iPhone. It cannot be undone.": {
        "fr": "Cela supprime définitivement vos séances, profil, règles, expériences, environnement et Manuel de cet iPhone. Action irréversible.",
        "es": "Esto borra permanentemente tus sesiones, perfil, reglas, experimentos, entorno y Manual de este iPhone. No se puede deshacer.",
        "de": "Dies löscht endgültig deine Sitzungen, dein Profil, Regeln, Experimente, Umgebung und Handbuch von diesem iPhone. Unumkehrbar.",
        "it": "Questo cancella per sempre sessioni, profilo, regole, esperimenti, ambiente e Manuale da questo iPhone. Non si può annullare.",
    },
    "Confirm permanent deletion": {
        "fr": "Confirmer la suppression définitive",
        "es": "Confirmar eliminación definitiva",
        "de": "Endgültige Löschung bestätigen",
        "it": "Conferma eliminazione definitiva",
    },
    "Permanently Delete": {
        "fr": "Supprimer définitivement",
        "es": "Eliminar permanentemente",
        "de": "Endgültig löschen",
        "it": "Elimina definitivamente",
    },
    "Everything will be deleted and REBOOT will return to its first launch. Your Apple subscription is managed separately in your Apple ID settings and is not deleted by this.": {
        "fr": "Tout sera supprimé et REBOOT reviendra à son premier lancement. Votre abonnement Apple est géré séparément dans les réglages de votre identifiant Apple et n'est pas supprimé par cette action.",
        "es": "Todo se borrará y REBOOT volverá a su primer arranque. Tu suscripción de Apple se gestiona por separado en los ajustes de tu ID de Apple y no se elimina con esto.",
        "de": "Alles wird gelöscht und REBOOT kehrt zum ersten Start zurück. Dein Apple-Abo wird separat in den Apple-ID-Einstellungen verwaltet und dadurch nicht gelöscht.",
        "it": "Tutto verrà cancellato e REBOOT tornerà al primo avvio. Il tuo abbonamento Apple è gestito separatamente nelle impostazioni ID Apple e non viene cancellato da questa azione.",
    },
    "View Web Version": {
        "fr": "Voir la version web",
        "es": "Ver versión web",
        "de": "Webversion ansehen",
        "it": "Vedi versione web",
    },

    # ================= NOTIFICATIONS =================
    "Today's Attention Practice": {
        "fr": "L'exercice d'attention du jour",
        "es": "El ejercicio de atención de hoy",
        "de": "Heutige Aufmerksamkeitsübung",
        "it": "L'esercizio di attenzione di oggi",
    },
    "Your focus session is ready. Take a few uninterrupted minutes to practice.": {
        "fr": "Votre séance est prête. Prenez quelques minutes sans interruption pour pratiquer.",
        "es": "Tu sesión está lista. Toma unos minutos sin interrupciones para practicar.",
        "de": "Deine Sitzung ist bereit. Nimm dir ein paar unterbrechungsfreie Minuten zum Üben.",
        "it": "La tua sessione è pronta. Prenditi qualche minuto senza interruzioni per praticare.",
    },
    "Weekly Attention Review": {
        "fr": "Revue hebdomadaire de l'attention",
        "es": "Revisión semanal de atención",
        "de": "Wöchentlicher Aufmerksamkeits-Review",
        "it": "Revisione settimanale dell'attenzione",
    },
    "A new weekly summary is available. See what REBOOT learned about your focus patterns.": {
        "fr": "Un nouveau résumé hebdomadaire est disponible. Voyez ce que REBOOT a appris sur vos schémas d'attention.",
        "es": "Hay un nuevo resumen semanal. Mira qué aprendió REBOOT sobre tus patrones de atención.",
        "de": "Eine neue Wochenübersicht ist verfügbar. Sieh, was REBOOT über deine Fokusmuster gelernt hat.",
        "it": "È disponibile un nuovo riepilogo settimanale. Scopri cosa ha imparato REBOOT sui tuoi schemi di attenzione.",
    },
    "Focus Window Starting Soon": {
        "fr": "Fenêtre de concentration imminente",
        "es": "Ventana de concentración a punto de empezar",
        "de": "Fokusfenster beginnt bald",
        "it": "Finestra di concentrazione in arrivo",
    },
}
