"""REBOOT product strings: EN source -> FR / ES / DE / IT.

Keys ARE the canonical English strings (String Catalog fallback design).
Voice: calm, precise, editorial. Non-clinical. Non-gamified. No idioms that
break tone. Mode names STAY / RECALL / EXPLAIN / NOTHING / OBSERVE and the
brand name REBOOT are never translated.
"""

STRINGS = {
    # ================= ONBOARDING =================
    "Your attention is being pulled apart.": {
        "fr": "Votre attention est en train d'être tirée en quatre.",
        "es": "Tu atención se está fragmentando.",
        "de": "Deine Aufmerksamkeit wird auseinandergerissen.",
        "it": "La tua attenzione viene spezzata.",
    },
    "Every notification, feed and interruption asks for the same thing: switch.": {
        "fr": "Chaque notification, chaque fil, chaque interruption demande la même chose : changer.",
        "es": "Cada notificación, cada feed, cada interrupción pide lo mismo: cambiar.",
        "de": "Jede Benachrichtigung, jeder Feed, jede Unterbrechung verlangt dasselbe: wechseln.",
        "it": "Ogni notifica, ogni feed, ogni interruzione chiede la stessa cosa: cambiare.",
    },
    "And what you repeat becomes easier to repeat.": {
        "fr": "Et ce que vous répétez devient plus facile à répéter.",
        "es": "Y lo que repites se vuelve más fácil de repetir.",
        "de": "Und was du wiederholst, wird leichter zu wiederholen.",
        "it": "E ciò che ripeti diventa più facile da ripetere.",
    },
    "See what's happening": {
        "fr": "Comprendre ce qui se passe",
        "es": "Ver qué está pasando",
        "de": "Verstehen, was passiert",
        "it": "Capire cosa succede",
    },
    "You're training yourself to switch.": {
        "fr": "Vous vous entraînez à changer d'attention.",
        "es": "Te estás entrenando para cambiar de tarea.",
        "de": "Du trainierst dich im Wechseln.",
        "it": "Ti stai allenando a cambiare.",
    },
    "Open. Scroll. Check. Change. Repeat.": {
        "fr": "Ouvrir. Faire défiler. Vérifier. Changer. Recommencer.",
        "es": "Abrir. Deslizar. Comprobar. Cambiar. Repetir.",
        "de": "Öffnen. Scrollen. Prüfen. Wechseln. Wiederholen.",
        "it": "Apri. Scorri. Controlli. Cambi. Ricominci.",
    },
    "The problem isn't that you've lost attention. Your environment keeps rewarding the opposite behaviour.": {
        "fr": "Le problème n'est pas que vous avez perdu votre attention. Votre environnement récompense sans cesse le comportement inverse.",
        "es": "El problema no es que hayas perdido atención. Tu entorno sigue premiando el comportamiento contrario.",
        "de": "Das Problem ist nicht, dass du deine Aufmerksamkeit verloren hast. Deine Umgebung belohnt ständig das Gegenteil.",
        "it": "Il problema non è che hai perso attenzione. Il tuo ambiente continua a premiare il comportamento opposto.",
    },
    "Cut the noise": {
        "fr": "Réduire le bruit",
        "es": "Cortar el ruido",
        "de": "Den Lärm abschalten",
        "it": "Taglia il rumore",
    },
    "Attention is a skill.": {
        "fr": "L'attention est une compétence.",
        "es": "La atención es una habilidad.",
        "de": "Aufmerksamkeit ist eine Fähigkeit.",
        "it": "L'attenzione è un'abilità.",
    },
    "Staying with one thing, returning after distraction and rebuilding what you learned can all be trained.": {
        "fr": "Rester sur une tâche, revenir après une distraction, approfondir ce que vous apprenez : tout cela peut s'entraîner.",
        "es": "Permanecer en una tarea, volver tras una distracción y profundizar lo aprendido se pueden entrenar.",
        "de": "Bei einer Sache bleiben, nach einer Ablenkung zurückkehren, Gelerntes vertiefen – all das lässt sich trainieren.",
        "it": "Restare su una cosa, tornare dopo una distrazione, approfondire ciò che hai imparato: tutto si può allenare.",
    },
    "REBOOT starts by measuring how you work today.": {
        "fr": "REBOOT commence par mesurer comment vous travaillez aujourd'hui.",
        "es": "REBOOT empieza midiendo cómo trabajas hoy.",
        "de": "REBOOT misst zuerst, wie du heute arbeitest.",
        "it": "REBOOT inizia misurando come lavori oggi.",
    },
    "Build my baseline": {
        "fr": "Établir mon point de départ",
        "es": "Crear mi punto de partida",
        "de": "Meinen Ausgangspunkt ermitteln",
        "it": "Crea la mia base",
    },
    "Less input. More depth.": {
        "fr": "Moins d'inputs. Plus de profondeur.",
        "es": "Menos estímulos. Más profundidad.",
        "de": "Weniger Input. Mehr Tiefe.",
        "it": "Meno input. Più profondità.",
    },
    "We'll change the conditions around you, train sustained attention, improve recall and help you design real deep-work sessions.": {
        "fr": "Nous modifierons vos conditions de travail, entraînerons l'attention soutenue, amélioreront la mémorisation et vous aideront à créer de vraies séances de travail profond.",
        "es": "Cambiaremos tus condiciones, entrenaremos la atención sostenida, mejoraremos la retención y te ayudaremos a diseñar sesiones reales de trabajo profundo.",
        "de": "Wir verändern deine Bedingungen, trainieren anhaltende Aufmerksamkeit, verbessern das Erinnern und helfen dir, echte Tiefenarbeit zu gestalten.",
        "it": "Cambieremo le condizioni intorno a te, alleneremo l'attenzione sostenuta, miglioreremo il ricordo e ti aiuteremo a creare vere sessioni di lavoro profondo.",
    },
    "No miracle. No dopamine detox. Just deliberate practice and better conditions.": {
        "fr": "Pas de miracle. Pas de « détox dopamine ». Juste une pratique délibérée et de meilleures conditions.",
        "es": "Nada milagroso. Nada de «detox de dopamina». Solo práctica deliberada y mejores condiciones.",
        "de": "Kein Wunder. Kein Dopamin-Detox. Nur bewusstes Üben und bessere Bedingungen.",
        "it": "Nessun miracolo. Nessun detox da dopamina. Solo pratica deliberata e condizioni migliori.",
    },
    "Show me the protocol": {
        "fr": "Voir le protocole",
        "es": "Ver el protocolo",
        "de": "Protokoll ansehen",
        "it": "Mostra il protocollo",
    },
    "90 days. Built around you.": {
        "fr": "90 jours. Construits autour de vous.",
        "es": "90 días. Diseñados a tu alrededor.",
        "de": "90 Tage. Um dich herum aufgebaut.",
        "it": "90 giorni. Costruiti intorno a te.",
    },
    "REBOOT learns from your sessions, experiments, environment, energy and Flow conditions — then adapts what comes next.": {
        "fr": "REBOOT apprend de vos séances, expériences, environnement, énergie et conditions de Flow — puis adapte la suite.",
        "es": "REBOOT aprende de tus sesiones, experimentos, entorno, energía y condiciones de Flow, y adapta lo que viene después.",
        "de": "REBOOT lernt aus deinen Sitzungen, Experimenten, deiner Umgebung, deiner Energie und deinen Flow-Bedingungen – und passt alles Weitere an.",
        "it": "REBOOT impara dalle tue sessioni, dai tuoi esperimenti, dall'ambiente, dall'energia e dalle condizioni di Flow, poi adatta ciò che segue.",
    },
    "No streak to protect. Miss a day and the program simply waits.": {
        "fr": "Aucune série à préserver. Un jour manqué et le programme attend, tout simplement.",
        "es": "Nada que perder por fallar un día. El programa simplemente espera.",
        "de": "Keine Serie zu verteidigen. Verpasst du einen Tag, wartet das Programm einfach.",
        "it": "Nessuna serie da proteggere. Se salti un giorno, il programma semplicemente aspetta.",
    },
    "Observe": {"fr": "Observer", "es": "Observar", "de": "Beobachten", "it": "Osservare"},
    "Adapt": {"fr": "S'adapter", "es": "Adaptarse", "de": "Anpassen", "it": "Adattarsi"},
    "Own it": {
        "fr": "En prendre le contrôle",
        "es": "Hacerlo tuyo",
        "de": "Selbst übernehmen",
        "it": "Renderlo tuo",
    },
    "One last thing": {
        "fr": "Une dernière chose",
        "es": "Una última cosa",
        "de": "Eine letzte Sache",
        "it": "Un'ultima cosa",
    },
    "Rebuild your attention.": {
        "fr": "Reconstruisez votre attention.",
        "es": "Reconstruye tu atención.",
        "de": "Baue deine Aufmerksamkeit neu auf.",
        "it": "Ricostruisci la tua attenzione.",
    },
    "The first week is calibration. We start with what you tell us, then REBOOT learns from what actually happens.": {
        "fr": "La première semaine sert d'étalonnage. Nous partons de ce que vous nous dites, puis REBOOT apprend de ce qui se passe vraiment.",
        "es": "La primera semana es de calibración. Empezamos con lo que nos cuentas y luego REBOOT aprende de lo que ocurre de verdad.",
        "de": "Die erste Woche ist Kalibrierung. Wir starten mit dem, was du uns sagst, dann lernt REBOOT aus dem, was wirklich passiert.",
        "it": "La prima settimana è di calibrazione. Partiamo da quello che ci dici, poi REBOOT impara da ciò che accade davvero.",
    },
    "Begin REBOOT": {"fr": "Commencer", "es": "Empezar", "de": "Beginnen", "it": "Inizia"},
    "Not now": {
        "fr": "Pas maintenant",
        "es": "Ahora no",
        "de": "Nicht jetzt",
        "it": "Non ora",
    },

    # ================= DIAGNOSIS QUESTIONS =================
    "What would feel meaningfully different 90 days from now?": {
        "fr": "Qu'est-ce qui serait vraiment différent dans 90 jours ?",
        "es": "¿Qué se sentiría realmente diferente dentro de 90 días?",
        "de": "Was würde sich nach 90 Tagen spürbar anders anfühlen?",
        "it": "Cosa si sentirebbe davvero diverso tra 90 giorni?",
    },
    "Choose everything that feels true.": {
        "fr": "Choisissez tout ce qui semble vrai.",
        "es": "Elige todo lo que sientas cierto.",
        "de": "Wähle alles, was sich richtig anfühlt.",
        "it": "Scegli tutto ciò che senti vero.",
    },
    "Work deeply for longer": {
        "fr": "Travailler en profondeur plus longtemps",
        "es": "Trabajar en profundidad durante más tiempo",
        "de": "Länger konzentriert tief arbeiten",
        "it": "Lavorare in profondità più a lungo",
    },
    "Stop compulsive checking": {
        "fr": "Arrêter les vérifications compulsives",
        "es": "Dejar de comprobar todo el tiempo",
        "de": "Aufhören, ständig zu checken",
        "it": "Smettere di controllare d'impulso",
    },
    "Stay with one thing": {
        "fr": "Rester concentré sur une seule chose",
        "es": "Permanecer en una sola cosa",
        "de": "Bei einer Sache bleiben",
        "it": "Restare su una cosa sola",
    },
    "Study without drifting": {
        "fr": "Étudier sans se disperser",
        "es": "Estudiar sin dispersarme",
        "de": "Ohne Abschweifen lernen",
        "it": "Studiare senza dispersione",
    },
    "Read with full attention": {
        "fr": "Lire avec toute son attention",
        "es": "Leer con toda la atención",
        "de": "Mit voller Aufmerksamkeit lesen",
        "it": "Leggere con tutta l'attenzione",
    },
    "Remember what I consume": {
        "fr": "Retenir ce que je consomme",
        "es": "Recordar lo que consumo",
        "de": "Behalten, was ich aufnehme",
        "it": "Ricordare ciò che consumo",
    },
    "Finish difficult tasks": {
        "fr": "Terminer les tâches difficiles",
        "es": "Terminar las tareas difíciles",
        "de": "Schwierige Aufgaben abschließen",
        "it": "Finire le attività difficili",
    },
    "A calmer relationship with my phone": {
        "fr": "Une relation plus calme avec mon téléphone",
        "es": "Una relación más tranquila con mi teléfono",
        "de": "Ein ruhigeres Verhältnis zum Handy",
        "it": "Un rapporto più sereno col telefono",
    },
    "Which part feels hardest right now?": {
        "fr": "Quelle partie semble la plus difficile en ce moment ?",
        "es": "¿Qué parte resulta más difícil ahora mismo?",
        "de": "Welcher Teil fühlt sich gerade am schwersten an?",
        "it": "Quale parte risulta più difficile adesso?",
    },
    "The honest one, not the most admirable one.": {
        "fr": "La réponse honnête, pas la plus admirable.",
        "es": "La respuesta sincera, no la más admirable.",
        "de": "Die ehrliche Antwort, nicht die bewundernswerteste.",
        "it": "La risposta sincera, non quella più ammirevole.",
    },
    "Getting started": {
        "fr": "Commencer",
        "es": "Empezar",
        "de": "Anfangen",
        "it": "Iniziare",
    },
    "Staying with one thing": {
        "fr": "Rester sur une même chose",
        "es": "Mantenerme en una cosa",
        "de": "Dranbleiben",
        "it": "Restare concentrato",
    },
    "Resisting the urge to check": {
        "fr": "Résister à l'envie de vérifier",
        "es": "Resistir las ganas de mirar el teléfono",
        "de": "Dem Check-Impuls widerstehen",
        "it": "Resistere alla voglia di controllare",
    },
    "Returning after an interruption": {
        "fr": "Revenir après une interruption",
        "es": "Volver tras una interrupción",
        "de": "Nach einer Unterbrechung zurückkehren",
        "it": "Tornare dopo un'interruzione",
    },
    "Remembering what I just read or watched": {
        "fr": "Retenir ce que je viens de lire ou de voir",
        "es": "Recordar lo que acabo de leer o ver",
        "de": "Behalten, was ich gerade gelesen oder gesehen habe",
        "it": "Ricordare cosa ho appena letto o visto",
    },
    "Quieting mental noise": {
        "fr": "Apaiser le bruit mental",
        "es": "Callar el ruido mental",
        "de": "Gedankenrauschen beruhigen",
        "it": "Silenzare il rumore mentale",
    },
    "Not sure yet": {
        "fr": "Je ne sais pas encore",
        "es": "Aún no lo sé",
        "de": "Weiß ich noch nicht",
        "it": "Non lo so ancora",
    },
    "Where does your attention break most?": {
        "fr": "Où votre attention se brise-t-elle le plus ?",
        "es": "¿Dónde se rompe más tu atención?",
        "de": "Wo bricht deine Aufmerksamkeit am häufigsten?",
        "it": "Dove si spezza di più la tua attenzione?",
    },
    "Where the break actually happens, not what bothers you most.": {
        "fr": "Là où la rupture se produit vraiment, pas ce qui vous déplaît le plus.",
        "es": "Donde ocurre de verdad, no lo que más molesta.",
        "de": "Wo der Abbruch wirklich passiert, nicht was dich am meisten stört.",
        "it": "Dove avviene davvero, non ciò che infastidisce di più.",
    },
    "The phone": {"fr": "Le téléphone", "es": "El teléfono", "de": "Das Handy", "it": "Il telefono"},
    "Notifications": {
        "fr": "Les notifications",
        "es": "Las notificaciones",
        "de": "Benachrichtigungen",
        "it": "Le notifiche",
    },
    "Social apps": {
        "fr": "Les réseaux sociaux",
        "es": "Las apps sociales",
        "de": "Social Apps",
        "it": "Le app social",
    },
    "Browser tabs": {
        "fr": "Les onglets du navigateur",
        "es": "Las pestañas del navegador",
        "de": "Browser-Tabs",
        "it": "Le schede del browser",
    },
    "My own thoughts": {
        "fr": "Mes propres pensées",
        "es": "Mis propios pensamientos",
        "de": "Meine eigenen Gedanken",
        "it": "I miei stessi pensieri",
    },
    "People around me": {
        "fr": "Les personnes autour de moi",
        "es": "La gente a mi alrededor",
        "de": "Menschen um mich herum",
        "it": "Le persone intorno",
    },
    "Tiredness": {"fr": "La fatigue", "es": "El cansancio", "de": "Müdigkeit", "it": "La stanchezza"},
    "Unclear": {"fr": "Pas clair", "es": "No lo tengo claro", "de": "Unklar", "it": "Non è chiaro"},
    "And if only one of these could fully change, which one?": {
        "fr": "Et si une seule de ces choses pouvait totalement changer, laquelle ?",
        "es": "Y si solo una pudiera cambiar por completo, ¿cuál?",
        "de": "Und wenn sich nur eine davon völlig ändern könnte – welche?",
        "it": "E se una sola di queste potesse cambiare del tutto, quale?",
    },
    "This becomes the direction everything else adapts around.": {
        "fr": "Elle devient la direction autour de laquelle tout le reste s'adapte.",
        "es": "Se convierte en la dirección sobre la que se adapta todo lo demás.",
        "de": "Sie wird zur Richtung, um die sich alles andere anpasst.",
        "it": "Diventa la direzione attorno alla quale si adatta tutto il resto.",
    },
    "When you start something demanding, how long before you usually feel pulled away?": {
        "fr": "Quand vous commencez une tâche exigeante, au bout de combien de temps vous sentez-vous généralement détourné ?",
        "es": "Cuando empiezas algo exigente, ¿cuánto tardas normalmente en sentirte arrastrado a otra cosa?",
        "de": "Wenn du etwas Anspruchsvolles beginnst – nach wie lange fühlst du dich meistens abgelenkt?",
        "it": "Quando inizi qualcosa di impegnativo, dopo quanto tempo di solito ti senti attratto altrove?",
    },
    "A typical day, not your best one.": {
        "fr": "Une journée ordinaire, pas votre meilleure.",
        "es": "Un día normal, no tu mejor día.",
        "de": "Ein typischer Tag, nicht dein bester.",
        "it": "Una giornata normale, non la migliore.",
    },
    "Under 5 minutes": {
        "fr": "Moins de 5 minutes",
        "es": "Menos de 5 minutos",
        "de": "Unter 5 Minuten",
        "it": "Meno di 5 minuti",
    },
    "5 – 15 minutes": {
        "fr": "5 – 15 minutes",
        "es": "5 – 15 minutos",
        "de": "5 – 15 Minuten",
        "it": "5 – 15 minuti",
    },
    "15 – 30 minutes": {
        "fr": "15 – 30 minutes",
        "es": "15 – 30 minutos",
        "de": "15 – 30 Minuten",
        "it": "15 – 30 minuti",
    },
    "30 – 60 minutes": {
        "fr": "30 – 60 minutes",
        "es": "30 – 60 minutos",
        "de": "30 – 60 Minuten",
        "it": "30 – 60 minuti",
    },
    "Usually past an hour": {
        "fr": "Généralement plus d'une heure",
        "es": "Normalmente más de una hora",
        "de": "Meist über eine Stunde",
        "it": "Di solito oltre un'ora",
    },
    "Depends heavily on the task": {
        "fr": "Cela dépend beaucoup de la tâche",
        "es": "Depende mucho de la tarea",
        "de": "Hängt stark von der Aufgabe ab",
        "it": "Dipende molto dall'attività",
    },
    "When the work becomes uncomfortable, what usually happens?": {
        "fr": "Quand le travail devient inconfortable, que se passe-t-il généralement ?",
        "es": "Cuando el trabajo se hace incómodo, ¿qué pasa normalmente?",
        "de": "Wenn die Arbeit unbequem wird, was passiert dann meistens?",
        "it": "Quando il lavoro diventa scomodo, cosa succede di solito?",
    },
    "I check my phone": {
        "fr": "Je vérifie mon téléphone",
        "es": "Miro mi teléfono",
        "de": "Ich checke mein Handy",
        "it": "Controllo il telefono",
    },
    "I open something else": {
        "fr": "J'ouvre autre chose",
        "es": "Abro otra cosa",
        "de": "Ich öffne etwas anderes",
        "it": "Apro altro",
    },
    "I keep going, but it loses depth": {
        "fr": "Je continue, mais ça perd en profondeur",
        "es": "Sigo, pero pierdo profundidad",
        "de": "Ich mache weiter, aber es verliert an Tiefe",
        "it": "Continuo, ma perde profondità",
    },
    "My mind wanders off": {
        "fr": "Mon esprit s'évade",
        "es": "Mi mente se va a otro lado",
        "de": "Meine Gedanken schweifen ab",
        "it": "La mente vaga altrove",
    },
    "I abandon the task": {
        "fr": "J'abandonne la tâche",
        "es": "Abandono la tarea",
        "de": "Ich gebe die Aufgabe auf",
        "it": "Abbandono l'attività",
    },
    "It varies": {"fr": "Ça varie", "es": "Varía", "de": "Es variiert", "it": "Varia"},
    "After getting distracted, what usually happens next?": {
        "fr": "Après une distraction, que se passe-t-il ensuite ?",
        "es": "Tras distraerte, ¿qué suele pasar después?",
        "de": "Was passiert meistens, nachdem du abgelenkt wurdest?",
        "it": "Dopo una distrazione, cosa succede di solito?",
    },
    "I come back fairly quickly": {
        "fr": "Je reviens assez vite",
        "es": "Vuelvo bastante rápido",
        "de": "Ich komme ziemlich schnell zurück",
        "it": "Torno abbastanza presto",
    },
    "Returning takes real effort": {
        "fr": "Revenir demande un vrai effort",
        "es": "Volver cuesta un esfuerzo real",
        "de": "Zurückkehren kostet echte Mühe",
        "it": "Tornare richiede un vero sforzo",
    },
    "I drift into something else instead": {
        "fr": "Je dérive vers autre chose à la place",
        "es": "Acabo derivando hacia otra cosa",
        "de": "Ich treibe stattdessen in etwas anderes",
        "it": "Finisco per derivare verso altro",
    },
    "The original task is usually lost": {
        "fr": "La tâche d'origine est généralement perdue",
        "es": "La tarea original suele perderse",
        "de": "Die ursprüngliche Aufgabe geht meist verloren",
        "it": "L'attività originale di solito si perde",
    },
    "What kind of work matters most right now?": {
        "fr": "Quel travail compte le plus pour vous en ce moment ?",
        "es": "¿Qué tipo de trabajo importa más ahora mismo?",
        "de": "Welche Art von Arbeit ist dir gerade am wichtigsten?",
        "it": "Che tipo di lavoro conta di più adesso?",
    },
    "REBOOT uses your real material, so it helps to know what it is.": {
        "fr": "REBOOT utilise votre vrai matériel, donc il est utile de savoir lequel.",
        "es": "REBOOT usa tu material real, así que ayuda saber cuál es.",
        "de": "REBOOT arbeitet mit deinem echten Material, daher hilft es, es zu kennen.",
        "it": "REBOOT usa il tuo materiale reale, quindi aiuta sapere qual è.",
    },
    "Studying": {"fr": "Étudier", "es": "Estudiar", "de": "Lernen", "it": "Studiare"},
    "Creative work": {
        "fr": "Travail créatif",
        "es": "Trabajo creativo",
        "de": "Kreative Arbeit",
        "it": "Lavoro creativo",
    },
    "Professional deep work": {
        "fr": "Travail professionnel en profondeur",
        "es": "Trabajo profesional en profundidad",
        "de": "Berufliche Tiefenarbeit",
        "it": "Lavoro professionale in profondità",
    },
    "Reading & learning": {
        "fr": "Lecture et apprentissage",
        "es": "Lectura y aprendizaje",
        "de": "Lesen und Lernen",
        "it": "Lettura e apprendimento",
    },
    "Building & coding": {
        "fr": "Construction et code",
        "es": "Construir y programar",
        "de": "Bauen und Programmieren",
        "it": "Costruire e programmare",
    },
    "A bit of everything": {
        "fr": "Un peu de tout",
        "es": "Un poco de todo",
        "de": "Ein bisschen von allem",
        "it": "Un po' di tutto",
    },
    "When does your attention naturally feel best?": {
        "fr": "Quand votre attention se sent-elle naturellement au mieux ?",
        "es": "¿Cuándo tu atención se siente naturalmente mejor?",
        "de": "Wann fühlt sich deine Aufmerksamkeit von Natur aus am besten an?",
        "it": "Quando la tua attenzione si sente naturalmente al meglio?",
    },
    "Early morning": {
        "fr": "Tôt le matin",
        "es": "Primera hora de la mañana",
        "de": "Früh am Morgen",
        "it": "Prima del mattino",
    },
    "Mid-morning": {
        "fr": "Milieu de matinée",
        "es": "Media mañana",
        "de": "Vormittag",
        "it": "Metà mattina",
    },
    "Afternoon": {"fr": "Après-midi", "es": "Tarde", "de": "Nachmittag", "it": "Pomeriggio"},
    "Evening": {"fr": "Soir", "es": "Noche", "de": "Abend", "it": "Sera"},
    "Late night": {
        "fr": "Fin de soirée",
        "es": "Madrugada",
        "de": "Späte Nacht",
        "it": "Tarda notte",
    },
    "No pattern I've noticed": {
        "fr": "Aucun schéma que j'aie remarqué",
        "es": "Ningún patrón que haya notado",
        "de": "Kein Muster, das ich bemerkt habe",
        "it": "Nessuno schema che abbia notato",
    },

    "Attention in general": {
        "fr": "L'attention en général",
        "es": "La atención en general",
        "de": "Aufmerksamkeit allgemein",
        "it": "L'attenzione in generale",
    },

    "Under 5 min": {
        "fr": "Moins de 5 min",
        "es": "Menos de 5 min",
        "de": "Unter 5 Min.",
        "it": "Meno di 5 min",
    },
    "60+ minutes": {
        "fr": "Plus de 60 minutes",
        "es": "Más de 60 minutos",
        "de": "Über 60 Minuten",
        "it": "Oltre 60 minuti",
    },
    # ================= DAILY GUIDANCE =================
    "RECENT PATTERN": {"fr": "MOTIF RÉCENT", "es": "PATRÓN RECIENTE", "de": "AKTUELLES MUSTER", "it": "SCHEMA RECENTE"},
    "TODAY'S SUGGESTION": {
        "fr": "SUGGESTION DU JOUR",
        "es": "SUGERENCIA DE HOY",
        "de": "HEUTIGER VORSCHLAG",
        "it": "SUGGERIMENTO DI OGGI",
    },
    "Your recent pattern is stable. Use REBOOT if you want to train, test, or review.": {
        "fr": "Ton schéma récent est stable. Utilise REBOOT si tu veux t'entraîner, tester ou revoir.",
        "es": "Tu patrón reciente es estable. Usa REBOOT si quieres entrenar, probar o repasar.",
        "de": "Dein aktuelles Muster ist stabil. Nutze REBOOT, wenn du trainieren, testen oder nachsehen willst.",
        "it": "Il tuo schema recente è stabile. Usa REBOOT se vuoi allenarti, provare o rivedere.",
    },
    "%d of %d": {
        "en": "%d of %d",
        "fr": "%d sur %d",
        "es": "%d de %d",
        "de": "%d von %d",
        "it": "%d di %d",
    },
    "Select to continue": {
        "fr": "Sélectionnez pour continuer",
        "es": "Elige para continuar",
        "de": "Auswählen zum Fortfahren",
        "it": "Seleziona per continuare",
    },
    "Observe your natural focus": {
        "fr": "Observe ton focus naturel",
        "es": "Observa tu foco natural",
        "de": "Beobachte deinen natürlichen Fokus",
        "it": "Osserva la tua concentrazione naturale",
    },
    "15 MIN · OBSERVE": {"fr": "15 MIN · OBSERVER", "es": "15 MIN · OBSERVAR", "de": "15 MIN · BEOBACHTEN", "it": "15 MIN · OSSERVARE"},
    "Start baseline": {
        "fr": "Démarrer la référence",
        "es": "Iniciar la referencia",
        "de": "Referenz starten",
        "it": "Avvia la base di riferimento",
    },
    "Day 1 measures how you normally work. Nothing about your environment changes yet.": {
        "fr": "Le Jour 1 mesure ta façon normale de travailler. Rien dans ton environnement ne change encore.",
        "es": "El Día 1 mide cómo trabajas normalmente. Nada de tu entorno cambia todavía.",
        "de": "Tag 1 misst, wie du normalerweise arbeitest. An deiner Umgebung ändert sich noch nichts.",
        "it": "Il Giorno 1 misura come lavori di norma. Nulla del tuo ambiente cambia ancora.",
    },
    "Give your mind less to react to.": {
        "fr": "Donne à ton esprit moins à quoi réagir.",
        "es": "Dale a tu mente menos a lo que reaccionar.",
        "de": "Gib deinem Geist weniger, worauf es reagieren kann.",
        "it": "Dai alla tua mente meno cose a cui reagire.",
    },
    "5 MIN · NOTHING": {"fr": "5 MIN · RIEN", "es": "5 MIN · NADA", "de": "5 MIN · NICHTS", "it": "5 MIN · NIENTE"},
    "Begin reset": {"fr": "Commencer la pause", "es": "Iniciar el reset", "de": "Reset beginnen", "it": "Avvia il reset"},
    "Your last session felt hard. Today is lighter on purpose — that is how load stays survivable.": {
        "fr": "Ta dernière séance a été difficile. Aujourd'hui est plus léger à dessein — c'est ainsi que la charge reste soutenable.",
        "es": "Tu última sesión se sintió dura. Hoy es más ligero a propósito: así la carga se mantiene sostenible.",
        "de": "Deine letzte Sitzung fühlte sich hart an. Heute ist absichtlich leichter – so bleibt die Last tragbar.",
        "it": "La tua ultima sessione è stata pesante. Oggi è più leggera apposta: così il carico resta sostenibile.",
    },
    "You know how you start best.": {
        "fr": "Tu sais comment tu démarres le mieux.",
        "es": "Ya sabes cómo empiezas mejor.",
        "de": "Du weißt, wie du am besten startest.",
        "it": "Sai già come inizi al meglio.",
    },
    "Start focus block": {
        "fr": "Démarrer un bloc de focus",
        "es": "Iniciar bloque de foco",
        "de": "Fokusblock starten",
        "it": "Avvia blocco di focus",
    },
    "Open your Operating Manual": {
        "fr": "Ouvrir ton Manuel",
        "es": "Abrir tu Manual",
        "de": "Dein Handbuch öffnen",
        "it": "Apri il tuo Manuale",
    },
    "You own your attention system now. REBOOT suggests; you decide.": {
        "fr": "Ton système d'attention t'appartient. REBOOT suggère ; tu décides.",
        "es": "Tu sistema de atención ya es tuyo. REBOOT sugiere; tú decides.",
        "de": "Dein Aufmerksamkeitssystem gehört dir. REBOOT schlägt vor; du entscheidest.",
        "it": "Il tuo sistema di attenzione è ormai tuo. REBOOT suggerisce; decidi tu.",
    },
    "Keep your phone outside arm's reach": {
        "fr": "Garde ton téléphone hors de portée de bras",
        "es": "Deja el teléfono fuera del alcance del brazo",
        "de": "Halte dein Handy außer Reichweite",
        "it": "Tieni il telefono fuori portata di braccio",
    },

    # ================= MODE-AWARE EXPLANATIONS =================
    "Today you explain the main idea out loud or in writing — fluency reveals what actually stuck.": {
        "fr": "Aujourd'hui, tu expliques l'idée principale à voix haute ou par écrit — la fluidité révèle ce qui est vraiment resté.",
        "es": "Hoy explicas la idea principal en voz alta o por escrito: la fluidez revela lo que de verdad quedó.",
        "de": "Heute erklärst du die Hauptidee laut oder schriftlich – die Flüsigkeit zeigt, was wirklich hängen geblieben ist.",
        "it": "Oggi spieghi l'idea principale a voce alta o per iscritto: la fluidità rivela ciò che è davvero rimasto.",
    },
    "A deliberate pause with no input. Notice what makes adding nothing difficult.": {
        "fr": "Une pause délibérée sans aucun input. Remarque ce qui rend le « ne rien ajouter » difficile.",
        "es": "Una pausa deliberada sin nada de entrada. Observa qué hace difícil no añadir nada.",
        "de": "Eine bewusste Pause ohne jeden Input. Merke, worin das Nichts-hinzufügen schwerfällt.",
        "it": "Una pausa deliberata senza alcun input. Nota cosa rende difficile non aggiungere nulla.",
    },
    "Recent recall attempts lost most of the material. Today closes the source sooner and asks for more.": {
        "fr": "Les derniers essais de rappel ont perdu l'essentiel du contenu. Aujourd'hui, on ferme la source plus tôt et on en demande plus.",
        "es": "Los últimos intentos de recuerdo perdieron la mayor parte del material. Hoy se cierra la fuente antes y se pide más.",
        "de": "Die letzten Abruf-Versuche haben das meiste Material verloren. Heute wird die Quelle früher geschlossen und mehr verlangt.",
        "it": "I recenti tentativi di richiamo hanno perso gran parte del materiale. Oggi si chiude la fonte prima e si chiede di più.",
    },
    "Remembering is depth's proof. Today tests how much of the harder material comes back without the source.": {
        "fr": "Se souvenir est la preuve de la profondeur. Aujourd'hui teste combien du contenu difficile revient sans la source.",
        "es": "Recordar es la prueba de la profundidad. Hoy pone a prueba cuánto del material difícil vuelve sin la fuente.",
        "de": "Erinnern ist der Beweis von Tiefe. Heute testet sich, wie viel des schwierigeren Materials ohne die Quelle zurückkommt.",
        "it": "Ricordare è la prova della profondità. Oggi si verifica quanto del materiale più difficile torna senza la fonte.",
    },
    "Today trains recall: close the source, then bring back what stayed with you.": {
        "fr": "Aujourd'hui entraîne le rappel : ferme la source, puis ramène ce qui est resté avec toi.",
        "es": "Hoy entrena el recuerdo: cierra la fuente y trae de vuelta lo que se quedó contigo.",
        "de": "Heute trainierst du Abruf: schließe die Quelle und hol zurück, was geblieben ist.",
        "it": "Oggi si allena il richiamo: chiudi la fonte e riporta ciò che è rimasto con te.",
    },
    "Observation first. Today watches when attention moves, especially near the start of a task.": {
        "fr": "L'observation d'abord. Aujourd'hui observe quand l'attention bouge, surtout au début d'une tâche.",
        "es": "Primero observar. Hoy se observa cuándo se mueve la atención, sobre todo al inicio de una tarea.",
        "de": "Zuerst Beobachten. Heute wird beobachtet, wann die Aufmerksamkeit wandert, besonders am Anfang einer Aufgabe.",
        "it": "Prima osservare. Oggi si osserva quando l'attenzione si muove, soprattutto all'inizio di un compito.",
    },
    "Watch what pulls today — noticing the pull precisely is what lets tomorrow's setup work.": {
        "fr": "Observe ce qui tire aujourd'hui — remarquer précisément la traction permet au réglage de demain de fonctionner.",
        "es": "Observa hoy qué tira de ti — notar con precisión el impulso es lo que hará funcionar el ajuste de mañana.",
        "de": "Beobachte heute, was zieht – den Zug genau zu bemerken macht das Setup von morgen wirksam.",
        "it": "Osserva oggi cosa tira — notare con precisione lo slittamento rende efficace il regolamento di domani.",
    },
    "This phase looks for the conditions around your deeper work. A real project is the cleanest probe.": {
        "fr": "Cette phase cherche les conditions de ton travail en profondeur. Un vrai projet est la sonde la plus nette.",
        "es": "Esta fase busca las condiciones de tu trabajo profundo. Un proyecto real es la prueba más limpia.",
        "de": "Diese Phase sucht die Bedingungen deiner Tiefenarbeit. Ein echtes Projekt ist der klarste Test.",
        "it": "Questa fase cerca le condizioni del tuo lavoro profondo. Un progetto reale è la prova più pulita.",
    },
    "Nothing gets optimized today. You observe what your attention actually does.": {
        "fr": "Rien n'est optimisé aujourd'hui. Tu observes ce que fait réellement ton attention.",
        "es": "Hoy no se optimiza nada. Observas lo que tu atención hace realmente.",
        "de": "Heute wird nichts optimiert. Du beobachtest, was deine Aufmerksamkeit wirklich tut.",
        "it": "Oggi non si ottimizza nulla. Osservi ciò che la tua attenzione fa davvero.",
    },
    "Focus holds once you're in. Today extends the stretch instead of changing the setup.": {
        "fr": "Le focus tient une fois installé. Aujourd'hui prolonge la séquence au lieu de changer le cadre.",
        "es": "El foco se mantiene una vez dentro. Hoy extiende el tramo en lugar de cambiar el entorno.",
        "de": "Der Fokus hält, wenn du drin bist. Heute wird die Strecke verlängert statt dem Setup geändert.",
        "it": "Il focus regge una volta dentro. Oggi si allunga il tratto invece di cambiare allestimento.",
    },
    "Switching happened recently — that's normal. What matters is coming back to the same task quickly.": {
        "fr": "Des changements sont survenus récemment — c'est normal. L'important est de revenir vite à la même tâche.",
        "es": "Hubo cambios recientemente — es normal. Lo que importa es volver rápido a la misma tarea.",
        "de": "Kürzlich gab es Wechsel – das ist normal. Entscheidend ist, schnell zur selben Aufgabe zurückzukehren.",
        "it": "Di recente ci sono stati cambiamenti — è normale. Conta tornare presto alla stessa attività.",
    },
    "You are ready to stay with something harder. Depth comes from difficulty held longer.": {
        "fr": "Tu peux rester sur quelque chose de plus difficile. La profondeur vient de la difficulté tenue plus longtemps.",
        "es": "Estás listo para quedarte con algo más difícil. La profundidad viene de sostener la dificultad más tiempo.",
        "de": "Du bist bereit für etwas Schwereres. Tiefe entsteht, wenn Schwierigkeit länger gehalten wird.",
        "it": "Sei pronto a restare su qualcosa di più difficile. La profondità nasce dalla difficoltà prolungata.",
    },
    "Reported energy is low today. The session gets shorter so quality doesn't have to.": {
        "fr": "L'énergie annoncée est basse aujourd'hui. La séance raccourcit pour que la qualité n'ait pas à le faire.",
        "es": "La energía reportada hoy está baja. La sesión se acorta para que la calidad no tenga que hacerlo.",
        "de": "Die gemeldete Energie ist heute niedrig. Die Sitzung wird kürzer, damit die Qualität es nicht muss.",
        "it": "L'energia dichiarata oggi è bassa. La sessione si accorcia così la qualità non deve farlo.",
    },
    "Physical setup shapes how long attention holds before the first pull.": {
        "fr": "L'aménagement physique façonne la durée pendant laquelle l'attention tient avant la première traction.",
        "es": "El entorno físico define cuánto se mantiene la atención antes del primer tirón.",
        "de": "Das physische Umfeld bestimmt, wie lange die Aufmerksamkeit vor dem ersten Zug hält.",
        "it": "L'allestimento fisico determina quanto a lungo l'attenzione regge prima del primo tiro.",
    },
    "Today compares one specific condition against your normal, so the question resolves with real sessions.": {
        "fr": "Aujourd'hui compare une condition précise à ta normale : la question se résout avec de vraies séances.",
        "es": "Hoy compara una condición concreta con tu normal: la pregunta se resuelve con sesiones reales.",
        "de": "Heute wird eine bestimmte Bedingung mit deinem Normalzustand verglichen – echte Sitzungen klären die Frage.",
        "it": "Oggi si confronta una condizione precisa col tuo normale: la domanda si risolve con sessioni vere.",
    },
    "One task, held longer than feels automatic. Today extends the stretch instead of changing the setup.": {
        "fr": "Une tâche, tenue plus longtemps que l'automatisme. Aujourd'hui prolonge la séquence sans changer le cadre.",
        "es": "Una tarea sostenida más allá de lo automático. Hoy extiende el tramo sin cambiar el entorno.",
        "de": "Eine Aufgabe, länger gehalten als es automatisch fällt. Heute wird die Strecke verlängert, nicht das Setup geändert.",
        "it": "Un'attività sostenuta oltre l'automatico. Oggi si allunga il tratto invece di cambiare allestimento.",
    },
    # ================= SESSION COMPLETION =================
    "Session complete": {"fr": "Séance terminée", "es": "Sesión completada", "de": "Sitzung abgeschlossen", "it": "Sessione completata"},
    "Session ended": {"fr": "Séance interrompue", "es": "Sesión finalizada", "de": "Sitzung beendet", "it": "Sessione terminata"},
    "Your baseline exists now.": {
        "fr": "Ta référence existe désormais.",
        "es": "Tu referencia ya existe.",
        "de": "Deine Referenz existiert jetzt.",
        "it": "Ora la tua base di riferimento esiste.",
    },
    "Done.": {"fr": "Fait.", "es": "Hecho.", "de": "Geschafft.", "it": "Fatto."},
    "That still tells us something.": {
        "fr": "Cela nous dit quand même quelque chose.",
        "es": "Eso todavía nos dice algo.",
        "de": "Das verrät uns trotzdem etwas.",
        "it": "Questo ci dice comunque qualcosa.",
    },
    "See what REBOOT noticed": {
        "fr": "Voir ce que REBOOT a remarqué",
        "es": "Ver lo que REBOOT notó",
        "de": "Sehen, was REBOOT bemerkt hat",
        "it": "Scopri cosa ha notato REBOOT",
    },
    "Continue": {"fr": "Continuer", "es": "Continuar", "de": "Weiter", "it": "Continua"},
    "You stayed for %d minutes. Nothing was optimized first.": {
        "fr": "Tu as tenu %d minutes. Rien n'a été optimisé avant tout.",
        "es": "Aguantaste %d minutos. Nada se optimizó primero.",
        "de": "Du hast %d Minuten durchgehalten. Zuerst wurde nichts optimiert.",
        "it": "Hai resistito %d minuti. Nulla è stato ottimizzato prima.",
    },
    "You observed for %d minutes.": {
        "fr": "Tu as observé pendant %d minutes.",
        "es": "Observaste durante %d minutos.",
        "de": "Du hast %d Minuten beobachtet.",
        "it": "Hai osservato per %d minuti.",
    },
    "You stayed with one task for %d minutes.": {
        "fr": "Tu es resté sur une tâche pendant %d minutes.",
        "es": "Te quedaste con una tarea durante %d minutos.",
        "de": "Du bist %d Minuten bei einer Aufgabe geblieben.",
        "it": "Sei restato su un'attività per %d minuti.",
    },
    "%d minutes of reading, then the source closed.": {
        "fr": "%d minutes de lecture, puis la source s'est fermée.",
        "es": "%d minutos de lectura y luego se cerró la fuente.",
        "de": "%d Minuten Lesen, dann schloss sich die Quelle.",
        "it": "%d minuti di lettura, poi la fonte si è chiusa.",
    },
    "You spent %d minutes and explained where it got hard.": {
        "fr": "Tu as passé %d minutes et expliqué où cela devenait difficile.",
        "es": "Dedicaste %d minutos y explicaste dónde se complicó.",
        "de": "Du hast %d Minuten investiert und erklärt, wo es schwer wurde.",
        "it": "Hai speso %d minuti e spiegato dove è diventato difficile.",
    },
    "%d minutes without adding anything new.": {
        "fr": "%d minutes sans rien ajouter de nouveau.",
        "es": "%d minutos sin añadir nada nuevo.",
        "de": "%d Minuten ohne etwas Neues hinzuzufügen.",
        "it": "%d minuti senza aggiungere nulla di nuovo.",
    },
    # ================= FLOW =================
    "Create your first project": {
        "fr": "Créer ton premier projet",
        "es": "Crea tu primer proyecto",
        "de": "Erstes Projekt anlegen",
        "it": "Crea il tuo primo progetto",
    },
    # ================= STARTING POINT V2 =================
    "WHAT YOU WANT": {"fr": "CE QUE VOUS VOULEZ", "es": "LO QUE QUIERES", "de": "WAS DU WILLST", "it": "CIO CHE VUOI"},
    "Still choosing": {"fr": "Choix en cours", "es": "Todavía eligiendo", "de": "Noch am Wählen", "it": "Ancora in scelta"},
    "STARTING HYPOTHESES": {"fr": "HYPOTHÈSES DE DÉPART", "es": "HIPÓTESIS INICIALES", "de": "STARTHYPOTHESEN", "it": "IPOTESI INIZIALI"},
    "%@ may be the hardest part right now.": {
        "fr": "%@ semble être la partie la plus difficile en ce moment.",
        "es": "%@ parece ser la parte más difícil ahora mismo.",
        "de": "%@ fühlt sich gerade am schwersten an.",
        "it": "%@ sembra la parte più difficile in questo momento.",
    },
    "%@ are a possible breaker.": {
        "fr": "%@ sont une source de rupture possible.",
        "es": "%@ son una posible fuente de ruptura.",
        "de": "%@ sind ein möglicher Unterbrecher.",
        "it": "%@ sono una possibile causa di rottura.",
    },
    "What pulls your attention is still unclear — Day 1 watches for it.": {
        "fr": "Ce qui attire votre attention reste flou — le Jour 1 y veille.",
        "es": "Lo que atrae tu atención aún no está claro — el Día 1 lo observará.",
        "de": "Was deine Aufmerksamkeit zieht, ist noch unklar – Tag 1 achtet darauf.",
        "it": "Ciò che attira la tua attenzione è ancora poco chiaro — il Giorno 1 osserverà.",
    },
    "Focus usually holds under 5 minutes before something pulls.": {
        "fr": "Le focus tient généralement moins de 5 minutes avant qu'une distraction survienne.",
        "es": "El foco suele aguantar menos de 5 minutos antes de que algo te arrastre.",
        "de": "Der Fokus hält meist unter 5 Minuten, bevor etwas zieht.",
        "it": "La concentrazione di solito regge meno di 5 minuti prima che qualcosa attragga.",
    },
    "Focus usually holds 5–15 minutes before something pulls.": {
        "fr": "Le focus tient généralement 5 à 15 minutes avant qu'une distraction survienne.",
        "es": "El foco suele aguantar entre 5 y 15 minutos antes de que algo te arrastre.",
        "de": "Der Fokus hält meist 5–15 Minuten, bevor etwas zieht.",
        "it": "La concentrazione di solito regge 5–15 minuti prima che qualcosa attragga.",
    },
    "You usually expect 15–30 minutes before feeling pulled away.": {
        "fr": "Vous tiendez généralement 15 à 30 minutes avant de vous sentir détourné.",
        "es": "Normalmente aguantas entre 15 y 30 minutos antes de sentirte arrastrado.",
        "de": "Meist hältst du 15–30 Minuten durch, bevor du dich abgelenkt fühlst.",
        "it": "Di solito resisti 15–30 minuti prima di sentirti attratto altrove.",
    },
    "Focus usually holds 30–60 minutes before something pulls.": {
        "fr": "Le focus tient généralement 30 à 60 minutes avant qu'une distraction survienne.",
        "es": "El foco suele aguantar entre 30 y 60 minutos antes de que algo te arrastre.",
        "de": "Der Fokus hält meist 30–60 Minuten, bevor etwas zieht.",
        "it": "La concentrazione di solito regge 30–60 minuti prima che qualcosa attragga.",
    },
    "You usually stay past an hour before feeling pulled away.": {
        "fr": "Vous tenez généralement plus d'une heure avant de vous sentir détourné.",
        "es": "Normalmente aguantas más de una hora antes de sentirte arrastrado.",
        "de": "Meist hältst du über eine Stunde durch, bevor du dich abgelenkt fühlst.",
        "it": "Di solito resisti oltre un'ora prima di sentirti attratto altrove.",
    },
    "After a distraction, returning %@": {
        "fr": "Après une distraction, revenir %@",
        "es": "Tras una distracción, volver %@",
        "de": "Nach einer Ablenkung fällt die Rückkehr %@ aus",
        "it": "Dopo una distrazione, tornare risulta %@",
    },
    "How you return after distraction isn't measured yet — Day 1 will test it.": {
        "fr": "La façon dont vous revenez après une distraction n'est pas encore mesurée — le Jour 1 la testera.",
        "es": "Cómo vuelves tras una distracción aún no se ha medido — el Día 1 lo pondrá a prueba.",
        "de": "Wie du nach einer Ablenkung zurückkehrst, ist noch nicht gemessen – Tag 1 testet es.",
        "it": "Come torni dopo una distrazione non è ancora misurato — il Giorno 1 lo verificherà.",
    },
    "WHAT REBOOT WILL MEASURE": {"fr": "CE QUE REBOOT MESURERA", "es": "LO QUE REBOOT MEDIRÁ", "de": "WAS REBOOT MISST", "it": "COSA MISURERÀ REBOOT"},
    "Your actual focus window.": {
        "fr": "Votre vraie fenêtre d'attention.",
        "es": "Tu ventana real de concentración.",
        "de": "Dein echtes Fokusfenster.",
        "it": "La tua vera finestra di concentrazione.",
    },
    "What really pulls you away.": {
        "fr": "Ce qui vous détache vraiment.",
        "es": "Lo que realmente te arrastra.",
        "de": "Was dich wirklich abzieht.",
        "it": "Cosa ti attrae davvero altrove.",
    },
    "How you return.": {
        "fr": "Comment vous revenez.",
        "es": "Cómo vuelves.",
        "de": "Wie du zurückkommst.",
        "it": "Come torni.",
    },
    "Which conditions consistently help.": {
        "fr": "Quelles conditions aident durablement.",
        "es": "Qué condiciones ayudan de forma constante.",
        "de": "Welche Bedingungen dauerhaft helfen.",
        "it": "Quali condizioni aiutano costantemente.",
    },
    "Observed evidence outweighs every answer above.": {
        "fr": "Les observations priment sur chaque réponse ci-dessus.",
        "es": "La evidencia observada pesa más que cada respuesta anterior.",
        "de": "Beobachtete Evidenz wiegt schwerer als jede Antwort oben.",
        "it": "L'evidenza osservata pesa più di ogni risposta sopra.",
    },
    # ================= STARTING POINT REPORT =================
    "Your starting point.": {
        "fr": "Votre point de départ.",
        "es": "Tu punto de partida.",
        "de": "Dein Ausgangspunkt.",
        "it": "Il tuo punto di partenza.",
    },
    "This is not a verdict. It is where REBOOT starts — and the first week begins replacing these answers with what actually happens.": {
        "fr": "Ce n'est pas un verdict. C'est là où REBOOT commence — et la première semaine remplace ces réponses par ce qui se passe réellement.",
        "es": "Esto no es un veredicto. Es donde empieza REBOOT, y la primera semana comienza a sustituir estas respuestas por lo que ocurre de verdad.",
        "de": "Dies ist kein Urteil. Hier beginnt REBOOT – und die erste Woche ersetzt diese Antworten durch das, was wirklich passiert.",
        "it": "Questo non è un verdetto. È dove REBOOT inizia, e la prima settimana comincia a sostituire queste risposte con ciò che accade davvero.",
    },
    "You told reboot": {
        "fr": "Vous avez dit à reboot",
        "es": "Le dijiste a reboot",
        "de": "Du hast reboot gesagt",
        "it": "Hai detto a reboot",
    },
    "Not chosen yet": {
        "fr": "Pas encore choisi",
        "es": "Aún sin elegir",
        "de": "Noch nicht gewählt",
        "it": "Non ancora scelto",
    },
    "Still unclear — Day 1 watches for it": {
        "fr": "Encore flou — le Jour 1 y veille",
        "es": "Todavía sin claridad — el Día 1 lo observará",
        "de": "Noch unklar – Tag 1 achtet darauf",
        "it": "Ancora poco chiaro — il Giorno 1 osserverà",
    },
    "Main breaker": {
        "fr": "Principale source de rupture",
        "es": "Principal fuente de ruptura",
        "de": "Hauptunterbrecher",
        "it": "Principale causa di rottura",
    },
    "Not identified yet": {
        "fr": "Pas encore identifié",
        "es": "Aún sin identificar",
        "de": "Noch nicht identifiziert",
        "it": "Non ancora identificato",
    },
    "Focus window": {
        "fr": "Fenêtre d'attention",
        "es": "Ventana de atención",
        "de": "Fokusfenster",
        "it": "Finestra di attenzione",
    },
    "Unmeasured": {
        "fr": "Non mesuré",
        "es": "Sin medir",
        "de": "Ungemessen",
        "it": "Non misurato",
    },
    "Returning after distraction": {
        "fr": "Le retour après distraction",
        "es": "Volver tras la distracción",
        "de": "Rückkehr nach Ablenkung",
        "it": "Il ritorno dopo la distrazione",
    },
    "When it gets hard": {
        "fr": "Quand ça devient difficile",
        "es": "Cuando se pone difícil",
        "de": "Wenn es schwer wird",
        "it": "Quando diventa difficile",
    },
    "Work that matters now": {
        "fr": "Le travail qui compte maintenant",
        "es": "El trabajo que importa ahora",
        "de": "Arbeit, die jetzt zählt",
        "it": "Il lavoro che conta ora",
    },
    "Best hours": {
        "fr": "Meilleures heures",
        "es": "Mejores horas",
        "de": "Beste Stunden",
        "it": "Migliori ore",
    },
    "What you told us": {
        "fr": "Ce que vous nous avez dit",
        "es": "Lo que nos contaste",
        "de": "Was du uns gesagt hast",
        "it": "Cosa ci hai detto",
    },
    "Hardest part": {
        "fr": "Partie la plus difficile",
        "es": "Lo más difícil",
        "de": "Der schwerste Teil",
        "it": "La parte più difficile",
    },
    "Early morning ": {
        "fr": "Tôt le matin ",
        "es": "Primera hora ",
        "de": "Frühmorgens ",
        "it": "Primo mattino ",
    },
    "Mid-morning ": {
        "fr": "Milieu de matinée ",
        "es": "Media mañana ",
        "de": "Vormittag ",
        "it": "Metà mattina ",
    },
    "What reboot will learn instead": {
        "fr": "Ce que reboot apprendra à la place",
        "es": "Lo que reboot aprenderá en su lugar",
        "de": "Was reboot stattdessen lernt",
        "it": "Cosa imparerà reboot invece",
    },
    "Your real focus window, measured across sessions.": {
        "fr": "Votre vraie fenêtre d'attention, mesurée sur plusieurs séances.",
        "es": "Tu verdadera ventana de atención, medida entre sesiones.",
        "de": "Dein echtes Fokusfenster, über Sitzungen hinweg gemessen.",
        "it": "La tua vera finestra di attenzione, misurata sulle sessioni.",
    },
    "Whether the phone actually pulls you, or something else does.": {
        "fr": "Si c'est vraiment le téléphone qui vous attire — ou autre chose.",
        "es": "Si realmente te atrae el teléfono, o es otra cosa.",
        "de": "Ob wirklich das Handy zieht – oder etwas anderes.",
        "it": "Se è davvero il telefono ad attrarti, o qualcos'altro.",
    },
    "How quickly you return — and what makes returning easier.": {
        "fr": "À quelle vitesse vous revenez — et ce qui facilite le retour.",
        "es": "Qué tan rápido vuelves, y qué facilita el regreso.",
        "de": "Wie schnell du zurückkommst – und was die Rückkehr erleichtert.",
        "it": "Quanto rapidamente torni, e cosa rende il ritorno più facile.",
    },
    "Which conditions hold your deeper work.": {
        "fr": "Les conditions qui soutiennent votre travail en profondeur.",
        "es": "Qué condiciones sostienen tu trabajo profundo.",
        "de": "Welche Bedingungen deine Tiefenarbeit tragen.",
        "it": "Quali condizioni sostengono il tuo lavoro profondo.",
    },
    "None of these stay fixed. Observed evidence outweighs every answer above.": {
        "fr": "Rien de tout cela n'est figé. Les observations priment sur chaque réponse ci-dessus.",
        "es": "Nada de esto queda fijo. La evidencia observada pesa más que cada respuesta anterior.",
        "de": "Nichts davon bleibt fest. Beobachtete Evidenz wiegt schwerer als jede Antwort oben.",
        "it": "Nulla di questo resta fisso. L'evidenza osservata pesa più di ogni risposta sopra.",
    },
    "Status: Calibrating": {
        "fr": "Statut : étalonnage",
        "es": "Estado: calibrando",
        "de": "Status: Kalibrierung",
        "it": "Stato: calibrazione",
    },
    "Day 1 of 90 · your plan adapts as REBOOT observes you": {
        "fr": "Jour 1 sur 90 · votre plan s'adapte pendant que REBOOT vous observe",
        "es": "Día 1 de 90 · tu plan se adapta mientras REBOOT te observa",
        "de": "Tag 1 von 90 · dein Plan passt sich an, während REBOOT dich beobachtet",
        "it": "Giorno 1 di 90 · il tuo piano si adatta mentre REBOOT ti osserva",
    },
    "Start day one": {
        "fr": "Commencer le jour un",
        "es": "Empezar el día uno",
        "de": "Tag eins beginnen",
        "it": "Inizia il giorno uno",
    },
    "Retake the diagnosis": {
        "fr": "Refaire le diagnostic",
        "es": "Repetir el diagnóstico",
        "de": "Diagnose wiederholen",
        "it": "Rifare la diagnosi",
    },
    "REBOOT trains attention behaviors. It doesn't diagnose anything or measure your brain.": {
        "fr": "REBOOT entraîne des comportements d'attention. Il ne diagnostique rien et ne mesure pas votre cerveau.",
        "es": "REBOOT entrena comportamientos de atención. No diagnostica nada ni mide tu cerebro.",
        "de": "REBOOT trainiert Aufmerksamkeitsverhalten. Es diagnostiziert nichts und misst dein Gehirn nicht.",
        "it": "REBOOT allena comportamenti dell'attenzione. Non diagnostica nulla e non misura il tuo cervello.",
    },

    # ================= SHELL / COMMON =================
    "Today": {"fr": "Aujourd'hui", "es": "Hoy", "de": "Heute", "it": "Oggi"},
    "Train": {"fr": "S'entraîner", "es": "Entrenar", "de": "Training", "it": "Allenati"},
    "Program": {"fr": "Programme", "es": "Programa", "de": "Programm", "it": "Programma"},
    "Profile": {"fr": "Profil", "es": "Perfil", "de": "Profil", "it": "Profilo"},
    "Done": {"fr": "OK", "es": "Listo", "de": "Fertig", "it": "Fatto"},
    "Cancel": {"fr": "Annuler", "es": "Cancelar", "de": "Abbrechen", "it": "Annulla"},
    "Continue": {"fr": "Continuer", "es": "Continuar", "de": "Weiter", "it": "Continua"},
    "Close": {"fr": "Fermer", "es": "Cerrar", "de": "Schließen", "it": "Chiudi"},

    # ================= TODAY =================
    "COMPLETE": {"fr": "TERMINÉ", "es": "COMPLETADO", "de": "ABGESCHLOSSEN", "it": "COMPLETATO"},
    "OWN MODE": {"fr": "MODE PROPRE", "es": "MODO PROPIO", "de": "EIGENER MODUS", "it": "MODO PROPRIO"},
    "BEFORE YOU START": {
        "fr": "AVANT DE COMMENCER",
        "es": "ANTES DE EMPEZAR",
        "de": "BEVOR DU BEGINNST",
        "it": "PRIMA DI INIZIARE",
    },
    "Done — I'm set up": {
        "fr": "C'est fait — je suis prêt",
        "es": "Hecho — estoy listo",
        "de": "Erledigt – bin bereit",
        "it": "Fatto — sono pronto",
    },
    "Can't today": {
        "fr": "Impossible aujourd'hui",
        "es": "Hoy no puedo",
        "de": "Heute nicht möglich",
        "it": "Oggi non posso",
    },
    "Today's session is complete.": {
        "fr": "La séance du jour est terminée.",
        "es": "La sesión de hoy está completa.",
        "de": "Die heutige Sitzung ist abgeschlossen.",
        "it": "La sessione di oggi è completata.",
    },
    "Avg focus": {"fr": "Focus moy.", "es": "Focus medio", "de": "Ø Fokus", "it": "Focus medio"},
    "Return": {"fr": "Retour", "es": "Retorno", "de": "Rückkehr", "it": "Ritorno"},
    "Strong": {"fr": "Fort", "es": "Fuerte", "de": "Stark", "it": "Forte"},
    "Fair": {"fr": "Correct", "es": "Aceptable", "de": "Ordentlich", "it": "Discreto"},
    "Weak": {"fr": "Faible", "es": "Débil", "de": "Schwach", "it": "Debole"},
    "min": {"fr": "min", "es": "min", "de": "Min.", "it": "min"},
    "One session recorded. REBOOT is still learning your patterns.": {
        "fr": "Une séance enregistrée. REBOOT apprend encore vos schémas.",
        "es": "Una sesión registrada. REBOOT todavía aprende tus patrones.",
        "de": "Eine Sitzung erfasst. REBOOT lernt noch deine Muster.",
        "it": "Una sessione registrata. REBOOT sta ancora imparando i tuoi schemi.",
    },
    "Nothing measured yet — Day 1 starts the record.": {
        "fr": "Rien de mesuré encore — le Jour 1 ouvre le dossier.",
        "es": "Nada medido aún — el Día 1 abre el historial.",
        "de": "Noch nichts gemessen – Tag 1 beginnt die Aufzeichnung.",
        "it": "Niente misurato ancora — il Giorno 1 apre il registro.",
    },
    "Your Attention Operating Manual remains alive and evolving.": {
        "fr": "Votre Manuel d'attention reste vivant et évolue.",
        "es": "Tu Manual de Atención sigue vivo y evolucionando.",
        "de": "Dein Aufmerksamkeits-Handbuch bleibt lebendig und entwickelt sich weiter.",
        "it": "Il tuo Manuale dell'Attenzione resta vivo e in evoluzione.",
    },
    "What happens today changes what comes next.": {
        "fr": "Ce qui se passe aujourd'hui change ce qui vient ensuite.",
        "es": "Lo que pasa hoy cambia lo que viene después.",
        "de": "Was heute passiert, verändert, was kommt.",
        "it": "Ciò che accade oggi cambia ciò che verrà.",
    },
    "Nothing needs adjusting today.": {
        "fr": "Rien à ajuster aujourd'hui.",
        "es": "Hoy no hay nada que ajustar.",
        "de": "Heute ist nichts anzupassen.",
        "it": "Oggi niente da sistemare.",
    },
    "NOTHING NEEDED": {
        "fr": "RIEN À FAIRE",
        "es": "NADA NECESARIO",
        "de": "NICHTS NÖTIG",
        "it": "NULLA DI NECESSARIO",
    },
    "SELF-DIRECTED": {
        "fr": "AUTONOME",
        "es": "AUTODIRIGIDO",
        "de": "SELBSTGESTEUERT",
        "it": "AUTODIRETTO",
    },
    "Open Operating Manual": {
        "fr": "Ouvrir le manuel d'attention",
        "es": "Abrir el manual de atención",
        "de": "Handbuch öffnen",
        "it": "Apri il manuale dell'attenzione",
    },
    "Opens the Attention Operating Manual": {
        "fr": "Ouvre le manuel d'attention",
        "es": "Abre el manual de atención",
        "de": "Öffnet das Aufmerksamkeits-Handbuch",
        "it": "Apre il manuale dell'attenzione",
    },
    "Opens the suggested destination": {
        "fr": "Ouvre la destination suggérée",
        "es": "Abre el destino sugerido",
        "de": "Öffnet das vorgeschlagene Ziel",
        "it": "Apre la destinazione suggerita",
    },
    "%d of %d program days completed": {
        "fr": "%d jours de programme complétés sur %d",
        "es": "%d de %d días de programa completados",
        "de": "%d von %d Programmtagen abgeschlossen",
        "it": "%d di %d giorni di programma completati",
    },
    "90 protocol days complete": {
        "fr": "90 jours de protocole terminés",
        "es": "90 días de protocolo completados",
        "de": "90 Protokolltage abgeschlossen",
        "it": "90 giorni di protocollo completati",
    },

    # ================= PAYWALL =================
    "paywall.price.year": {
        "en": "%@/year · cancel anytime",
        "fr": "%@/an · résiliable à tout moment",
        "es": "%@/año · cancela cuando quieras",
        "de": "%@/Jahr · jederzeit kündbar",
        "it": "%@/anno · cancella quando vuoi",
    },
    "paywall.price.month": {
        "en": "%@/month · billed monthly",
        "fr": "%@/mois · facturé mensuellement",
        "es": "%@/mes · facturación mensual",
        "de": "%@/Monat · monatliche Abrechnung",
        "it": "%@/mese · fatturazione mensile",
    },
    "paywall.unavailable": {
        "en": "Plans unavailable right now — check your connection and retry.",
        "fr": "Offres indisponibles pour le moment — vérifiez votre connexion puis réessayez.",
        "es": "Planes no disponibles ahora mismo — revisa tu conexión e inténtalo de nuevo.",
        "de": "Tarife gerade nicht verfügbar – Verbindung prüfen und erneut versuchen.",
        "it": "Piani non disponibili al momento — controlla la connessione e riprova.",
    },
    "Yearly": {"fr": "Annuel", "es": "Anual", "de": "Jährlich", "it": "Annuale"},
    "Monthly": {"fr": "Mensuel", "es": "Mensual", "de": "Monatlich", "it": "Mensile"},
    "7-day free trial": {
        "fr": "Essai gratuit de 7 jours",
        "es": "Prueba gratis de 7 días",
        "de": "7 Tage kostenlos testen",
        "it": "Prova gratuita di 7 giorni",
    },
    "Best value": {"fr": "Meilleure offre", "es": "Mejor precio", "de": "Bestes Angebot", "it": "Miglior prezzo"},
    "Start 7-Day Free Trial": {
        "fr": "Démarrer l'essai de 7 jours",
        "es": "Empezar prueba de 7 días",
        "de": "7-Tage-Test starten",
        "it": "Inizia la prova di 7 giorni",
    },
    "Continue the full program": {
        "fr": "Continuer le programme complet",
        "es": "Continuar el programa completo",
        "de": "Vollständiges Programm fortsetzen",
        "it": "Continua il programma completo",
    },
    "Restore purchases": {
        "fr": "Restaurer les achats",
        "es": "Restaurar compras",
        "de": "Käufe wiederherstellen",
        "it": "Ripristina acquisti",
    },
    "Terms of Service": {
        "fr": "Conditions d'utilisation",
        "es": "Términos del servicio",
        "de": "Nutzungsbedingungen",
        "it": "Termini di servizio",
    },
    "Privacy Policy": {
        "fr": "Politique de confidentialité",
        "es": "Política de privacidad",
        "de": "Datenschutzrichtlinie",
        "it": "Informativa sulla privacy",
    },
    "Subscriptions renew automatically unless canceled at least 24 hours before the end of the current billing cycle in your Apple ID Account Settings.": {
        "fr": "Les abonnements se renouvellent automatiquement sauf annulation au moins 24 h avant la fin de la période en cours dans les réglages de votre identifiant Apple.",
        "es": "Las suscripciones se renuevan automáticamente salvo cancelación al menos 24 horas antes del fin del ciclo actual en los ajustes de tu ID de Apple.",
        "de": "Abos verlängern sich automatisch, sofern nicht mindestens 24 Stunden vor Ende des aktuellen Zeitraums in den Apple-ID-Einstellungen gekündigt wird.",
        "it": "Gli abbonamenti si rinnovano automaticamente salvo disdetta almeno 24 ore prima della fine del periodo corrente nelle impostazioni dell'ID Apple.",
    },
    "UNDERSTAND": {"fr": "COMPRENDRE", "es": "ENTENDER", "de": "VERSTEHEN", "it": "CAPIRE"},
    "TRAIN": {"fr": "S'ENTRAÎNER", "es": "ENTRENAR", "de": "TRAINIEREN", "it": "ALLENARE"},
    "RESHAPE": {"fr": "REMODOLER", "es": "REMODELAR", "de": "UMGESTALTEN", "it": "RIDISEGNARE"},
    "LEARN": {"fr": "APPRENDRE", "es": "APRENDER", "de": "LERNEN", "it": "IMPARARE"},
    "LEAVE": {"fr": "TRANSMETTRE", "es": "DEJAR", "de": "ÜBERGEBEN", "it": "LASCIARE"},
    "What breaks your attention": {
        "fr": "Ce qui brise votre attention",
        "es": "Qué rompe tu atención",
        "de": "Was deine Aufmerksamkeit bricht",
        "it": "Cosa spezza la tua attenzione",
    },
    "Your sessions and honest self-reports surface the pulls that actually cost you focus.": {
        "fr": "Vos séances et vos réponses honnêtes révèlent les forces qui coûtent vraiment votre attention.",
        "es": "Tus sesiones y autoinformes sinceros revelan los impulsos que de verdad te cuestan foco.",
        "de": "Deine Sitzungen und ehrlichen Selbstauskünfte zeigen die Kräfte, die wirklich Fokus kosten.",
        "it": "Sessioni e autovalutazioni oneste rivelano gli impulsi che davvero ti costano concentrazione.",
    },
    "Staying, returning, recalling": {
        "fr": "Rester, revenir, retenir",
        "es": "Permanecer, volver, recordar",
        "de": "Bleiben, kehren, behalten",
        "it": "Restare, tornare, ricordare",
    },
    "One prescribed practice a day across five attention modes.": {
        "fr": "Une pratique prescrite par jour, parmi cinq modes d'attention.",
        "es": "Una práctica diaria recetada entre cinco modos de atención.",
        "de": "Eine tägliche Übung aus fünf Aufmerksamkeitsmodi.",
        "it": "Una pratica al giorno tra cinque modalità di attenzione.",
    },
    "Your environment": {
        "fr": "Votre environnement",
        "es": "Tu entorno",
        "de": "Deine Umgebung",
        "it": "Il tuo ambiente",
    },
    "Lighter friction first — distance, one-task browser, optional protection.": {
        "fr": "D'abord les frictions les plus légères — distance, navigateur à tâche unique, protection facultative.",
        "es": "Primero la fricción más ligera — distancia, navegador de una sola tarea, protección opcional.",
        "de": "Zuerst die leichteste Reibung – Abstand, Ein-Aufgaben-Browser, optionaler Schutz.",
        "it": "Prima l'attrito più leggero — distanza, browser a attività singola, protezione facoltativa.",
    },
    "The conditions that help you": {
        "fr": "Les conditions qui vous aident",
        "es": "Las condiciones que te ayudan",
        "de": "Die Bedingungen, die dir helfen",
        "it": "Le condizioni che ti aiutano",
    },
    "Tested against your own comparable sessions, not averages.": {
        "fr": "Testées contre vos propres séances comparables, pas des moyennes.",
        "es": "Probadas contra tus propias sesiones comparables, no contra promedios.",
        "de": "Getestet an deinen eigenen vergleichbaren Sitzungen, nicht an Durchschnitten.",
        "it": "Verificate sulle tue sessioni comparabili, non su medie.",
    },
    "An Operating Manual that's yours": {
        "fr": "Un manuel qui vous appartient",
        "es": "Un manual que es tuyo",
        "de": "Ein Handbuch, das dir gehört",
        "it": "Un manuale che è tuo",
    },
    "Day 90 ends with your evidence-backed manual; Own Mode keeps it useful.": {
        "fr": "Le jour 90 s'achève sur votre manuel fondé sur preuves ; le Mode propre le garde utile.",
        "es": "El día 90 termina con tu manual basado en evidencia; el Modo Propio lo mantiene útil.",
        "de": "Tag 90 endet mit deinem evidenzbasierten Handbuch; der Eigene Modus hält es nützlich.",
        "it": "Il giorno 90 si chiude col tuo manuale basato sull'evidenza; il Modo Proprio lo tiene utile.",
    },

    # ================= DAY 1 CONTINUATION =================
    "DAY 1 COMPLETE": {
        "fr": "JOUR 1 TERMINÉ",
        "es": "DÍA 1 COMPLETADO",
        "de": "TAG 1 ABGESCHLOSSEN",
        "it": "GIORNO 1 COMPLETATO",
    },
    "Your baseline is set.": {
        "fr": "Votre point de référence est posé.",
        "es": "Tu punto de referencia está fijado.",
        "de": "Dein Referenzpunkt steht.",
        "it": "Il tuo punto di riferimento è fissato.",
    },
    "REBOOT now knows how today felt — and everything from here is measured against it. Each session teaches the program something new about how your attention actually works.": {
        "fr": "REBOOT sait désormais comment ce jour s'est passé — et tout la suite se mesurera à cette référence. Chaque séance apprend au programme quelque chose de nouveau sur votre attention réelle.",
        "es": "REBOOT ya sabe cómo se sintió hoy, y todo lo que sigue se medirá contra eso. Cada sesión enseña al programa algo nuevo sobre cómo funciona realmente tu atención.",
        "de": "REBOOT weiß jetzt, wie sich dieser Tag angefühlt hat – alles Weitere wird daran gemessen. Jede Sitzung bringt dem Programm etwas Neues darüber bei, wie deine Aufmerksamkeit wirklich arbeitet.",
        "it": "REBOOT ormai sa com'è andata oggi, e tutto ciò che seguirà verrà misurato su questo. Ogni sessione insegna al programma qualcosa di nuovo su come funziona davvero la tua attenzione.",
    },
    "FIRST INSIGHT": {
        "fr": "PREMIÈRE OBSERVATION",
        "es": "PRIMERA OBSERVACIÓN",
        "de": "ERSTE ERKENNTNIS",
        "it": "PRIMA OSSERVAZIONE",
    },
    "Continue the 90-day program": {
        "fr": "Continuer le programme de 90 jours",
        "es": "Continuar el programa de 90 días",
        "de": "Das 90-Tage-Programm fortsetzen",
        "it": "Continua il programma di 90 giorni",
    },
    "The full program continues with a subscription. Your Day 1 session and insights stay yours either way.": {
        "fr": "La suite du programme nécessite un abonnement. Votre séance du Jour 1 et vos observations restent les vôtres dans tous les cas.",
        "es": "El programa completo continúa con una suscripción. Tu sesión del Día 1 y sus observaciones siguen siendo tuyas de todos modos.",
        "de": "Das volle Programm setzt mit einem Abo fort. Deine Tag-1-Sitzung und Erkenntnisse bleiben in jedem Fall deine.",
        "it": "Il programma completo continua con un abbonamento. La sessione del Giorno 1 e le osservazioni restano tue in ogni caso.",
    },

    # ================= DATA & PRIVACY =================
    "DATA & PRIVACY": {
        "fr": "DONNÉES & CONFIDENTIALITÉ",
        "es": "DATOS Y PRIVACIDAD",
        "de": "DATEN & DATENSCHUTZ",
        "it": "DATI E PRIVACY",
    },
    "Your attention, fully local": {
        "fr": "Votre attention, entièrement locale",
        "es": "Tu atención, completamente local",
        "de": "Deine Aufmerksamkeit, komplett lokal",
        "it": "La tua attenzione, interamente locale",
    },
    "REBOOT keeps everything on this device. There is no account, no cloud profile, and no analytics.": {
        "fr": "REBOOT conserve tout sur cet appareil. Aucun compte, aucun profil cloud, aucune analytique.",
        "es": "REBOOT guarda todo en este dispositivo. Sin cuentas, sin perfiles en la nube, sin analíticas.",
        "de": "REBOOT bewahrt alles auf diesem Gerät auf. Kein Konto, kein Cloud-Profil, keine Analyse-Tools.",
        "it": "REBOOT tiene tutto su questo dispositivo. Nessun account, nessun profilo cloud, nessuna analitica.",
    },
    "On-device storage only": {
        "fr": "Stockage uniquement sur l'appareil",
        "es": "Almacenamiento solo en el dispositivo",
        "de": "Speicherung nur auf dem Gerät",
        "it": "Archiviazione solo sul dispositivo",
    },
    "Diagnosis answers, session records, switch and return evidence, personal rules, experiment results, Fuel context, Flow projects, environment settings, and your Operating Manual are stored in the app's local sandbox on this iPhone. Nothing is transmitted to REBOOT or to anyone else.": {
        "fr": "Réponses du diagnostic, séances, preuves de changement et de retour, règles personnelles, résultats d'expériences, contexte Fuel, projets Flow, réglages d'environnement et votre Manuel sont stockés dans le bac à sable local de l'app sur cet iPhone. Rien n'est transmis à REBOOT ni à quiconque.",
        "es": "Respuestas del diagnóstico, sesiones, evidencia de cambios y retornos, reglas personales, resultados de experimentos, contexto Fuel, proyectos Flow, ajustes de entorno y tu Manual se guardan en el sandbox local de la app en este iPhone. Nada se transmite a REBOOT ni a nadie.",
        "de": "Antworten der Diagnose, Sitzungen, Wechsel- und Rückkehr-Evidenz, persönliche Regeln, Experimentresultate, Fuel-Kontext, Flow-Projekte, Umgebungseinstellungen und dein Handbuch liegen im lokalen Sandbox-Speicher der App auf diesem iPhone. Nichts wird an REBOOT oder Dritte übertragen.",
        "it": "Risposte della diagnosi, sessioni, evidenze di cambio e ritorno, regole personali, risultati degli esperimenti, contesto Fuel, progetti Flow, impostazioni d'ambiente e il tuo Manuale sono archiviati nella sandbox locale dell'app su questo iPhone. Nulla viene trasmesso a REBOOT o ad altri.",
    },
    "Export my REBOOT data": {
        "fr": "Exporter mes données REBOOT",
        "es": "Exportar mis datos de REBOOT",
        "de": "Meine REBOOT-Daten exportieren",
        "it": "Esporta i miei dati REBOOT",
    },
    "A single JSON file containing everything REBOOT knows: diagnosis answers, profile, sessions, rules, experiments, Flow projects and evidence, Fuel history, environment observations, reviews, and your Operating Manual. Nothing leaves your device except through the share sheet you control.": {
        "fr": "Un seul fichier JSON avec tout ce que REBOOT sait : réponses du diagnostic, profil, séances, règles, expériences, projets et preuves Flow, historique Fuel, observations d'environnement, revues et votre Manuel. Rien ne quitte votre appareil sauf via la feuille de partage que vous contrôlez.",
        "es": "Un único archivo JSON con todo lo que REBOOT sabe: respuestas del diagnóstico, perfil, sesiones, reglas, experimentos, proyectos y evidencia Flow, historial Fuel, observaciones del entorno, revisiones y tu Manual. Nada sale de tu dispositivo salvo por la hoja de compartir que tú controlas.",
        "de": "Eine einzige JSON-Datei mit allem, was REBOOT weiß: Diagnoseantworten, Profil, Sitzungen, Regeln, Experimente, Flow-Projekte und -Evidenz, Fuel-Verlauf, Umgebungsbeobachtungen, Reviews und dein Handbuch. Nichts verlässt dein Gerät außer über das Share-Sheet, das du steuerst.",
        "it": "Un unico file JSON con tutto ciò che REBOOT sa: risposte della diagnosi, profilo, sessioni, regole, esperimenti, progetti ed evidenze Flow, cronologia Fuel, osservazioni d'ambiente, revisioni e il tuo Manuale. Nulla lascia il tuo dispositivo se non tramite il foglio di condivisione che controlli.",
    },
    "Export as JSON": {
        "fr": "Exporter en JSON",
        "es": "Exportar como JSON",
        "de": "Als JSON exportieren",
        "it": "Esporta come JSON",
    },
    "Legal": {"fr": "Mentions légales", "es": "Legal", "de": "Rechtliches", "it": "Legale"},
    "Erase all data": {
        "fr": "Effacer toutes les données",
        "es": "Borrar todos los datos",
        "de": "Alle Daten löschen",
        "it": "Cancella tutti i dati",
    },
    "Permanently deletes everything REBOOT has learned — sessions, profile, rules, experiments, Flow projects, environment setup, notifications, and your Operating Manual — and returns the app to its first launch. Screen Time authorization and notification permission are Apple settings and remain; scheduled protections are removed.": {
        "fr": "Supprime définitivement tout ce que REBOOT a appris — séances, profil, règles, expériences, projets Flow, environnement, notifications et votre Manuel — et ramène l'app à son premier lancement. L'autorisation Temps d'écran et les notifications restent des réglages Apple ; les protections programmées sont retirées.",
        "es": "Borra definitivamente todo lo que REBOOT ha aprendido — sesiones, perfil, reglas, experimentos, proyectos Flow, entorno, notificaciones y tu Manual — y devuelve la app a su primer arranque. La autorización de Tiempo de uso y los permisos de notificación son ajustes de Apple y permanecen; las protecciones programadas se eliminan.",
        "de": "Löscht endgültig alles, was REBOOT gelernt hat — Sitzungen, Profil, Regeln, Experimente, Flow-Projekte, Umgebung, Mitteilungen und dein Handbuch — und bringt die App auf ihren ersten Start zurück. Bildschirmzeit-Freigabe und Mitteilungszugriff bleiben Apple-Einstellungen; geplante Schutzschichten werden entfernt.",
        "it": "Cancella definitivamente tutto ciò che REBOOT ha imparato — sessioni, profilo, regole, esperimenti, progetti Flow, ambiente, notifiche e il tuo Manuale — e riporta l'app al primo avvio. L'autorizzazione Tempo di utilizzo e le notifiche restano impostazioni Apple; le protezioni pianificate vengono rimosse.",
    },
    "I understand this cannot be undone": {
        "fr": "Je comprends que cette action est irréversible",
        "es": "Entiendo que esto no se puede deshacer",
        "de": "Ich verstehe, dass dies nicht rückgängig gemacht werden kann",
        "it": "Capisco che non si può annullare",
    },
    "Erase All REBOOT Data": {
        "fr": "Effacer toutes les données REBOOT",
        "es": "Borrar todos los datos de REBOOT",
        "de": "Alle REBOOT-Daten löschen",
        "it": "Cancella tutti i dati REBOOT",
    },
    "Erase all REBOOT data?": {
        "fr": "Effacer toutes les données REBOOT ?",
        "es": "¿Borrar todos los datos de REBOOT?",
        "de": "Alle REBOOT-Daten löschen?",
        "it": "Cancellare tutti i dati REBOOT?",
    },
    "Continue": {"fr": "Continuer", "es": "Continuar", "de": "Fortfahren", "it": "Continua"},
    "This permanently deletes your sessions, profile, rules, experiments, environment setup, and Operating Manual from this iPhone. It cannot be undone.": {
        "fr": "Cela supprime définitivement vos séances, profil, règles, expériences, environnement et Manuel de cet iPhone. Action irréversible.",
        "es": "Esto borra permanentemente tus sesiones, perfil, reglas, experimentos, entorno y Manual de este iPhone. No se puede deshacer.",
        "de": "Dies löscht endgültig deine Sitzungen, dein Profil, Regeln, Experimente, Umgebung und Handbuch von diesem iPhone. Unumkehrbar.",
        "it": "Questo cancella per sempre sessioni, profilo, regole, esperimenti, ambiente e Manuale da questo iPhone. Non si può annullare.",
    },
    "Confirm permanent deletion": {
        "fr": "Confirmer la suppression définitive",
        "es": "Confirmar eliminación definitiva",
        "de": "Endgültige Löschung bestätigen",
        "it": "Conferma eliminazione definitiva",
    },
    "Permanently Delete": {
        "fr": "Supprimer définitivement",
        "es": "Eliminar permanentemente",
        "de": "Endgültig löschen",
        "it": "Elimina definitivamente",
    },
    "Everything will be deleted and REBOOT will return to its first launch. Your Apple subscription is managed separately in your Apple ID settings and is not deleted by this.": {
        "fr": "Tout sera supprimé et REBOOT reviendra à son premier lancement. Votre abonnement Apple est géré séparément dans les réglages de votre identifiant Apple et n'est pas supprimé par cette action.",
        "es": "Todo se borrará y REBOOT volverá a su primer arranque. Tu suscripción de Apple se gestiona por separado en los ajustes de tu ID de Apple y no se elimina con esto.",
        "de": "Alles wird gelöscht und REBOOT kehrt zum ersten Start zurück. Dein Apple-Abo wird separat in den Apple-ID-Einstellungen verwaltet und dadurch nicht gelöscht.",
        "it": "Tutto verrà cancellato e REBOOT tornerà al primo avvio. Il tuo abbonamento Apple è gestito separatamente nelle impostazioni ID Apple e non viene cancellato da questa azione.",
    },
    "View Web Version": {
        "fr": "Voir la version web",
        "es": "Ver versión web",
        "de": "Webversion ansehen",
        "it": "Vedi versione web",
    },

    # ================= NOTIFICATIONS =================
    "Today's Attention Practice": {
        "fr": "L'exercice d'attention du jour",
        "es": "El ejercicio de atención de hoy",
        "de": "Heutige Aufmerksamkeitsübung",
        "it": "L'esercizio di attenzione di oggi",
    },
    "Your focus session is ready. Take a few uninterrupted minutes to practice.": {
        "fr": "Votre séance est prête. Prenez quelques minutes sans interruption pour pratiquer.",
        "es": "Tu sesión está lista. Toma unos minutos sin interrupciones para practicar.",
        "de": "Deine Sitzung ist bereit. Nimm dir ein paar unterbrechungsfreie Minuten zum Üben.",
        "it": "La tua sessione è pronta. Prenditi qualche minuto senza interruzioni per praticare.",
    },
    "Weekly Attention Review": {
        "fr": "Revue hebdomadaire de l'attention",
        "es": "Revisión semanal de atención",
        "de": "Wöchentlicher Aufmerksamkeits-Review",
        "it": "Revisione settimanale dell'attenzione",
    },
    "A new weekly summary is available. See what REBOOT learned about your focus patterns.": {
        "fr": "Un nouveau résumé hebdomadaire est disponible. Voyez ce que REBOOT a appris sur vos schémas d'attention.",
        "es": "Hay un nuevo resumen semanal. Mira qué aprendió REBOOT sobre tus patrones de atención.",
        "de": "Eine neue Wochenübersicht ist verfügbar. Sieh, was REBOOT über deine Fokusmuster gelernt hat.",
        "it": "È disponibile un nuovo riepilogo settimanale. Scopri cosa ha imparato REBOOT sui tuoi schemi di attenzione.",
    },
    "Focus Window Starting Soon": {
        "fr": "Fenêtre de concentration imminente",
        "es": "Ventana de concentración a punto de empezar",
        "de": "Fokusfenster beginnt bald",
        "it": "Finestra di concentrazione in arrivo",
    },
}
